/// Static C standard library reference data.

#[derive(Debug, Clone, Copy)]
pub struct CFunc {
    pub name: &'static str,
    pub header: &'static str,
    pub signature: &'static str,
    pub description: &'static str,
    pub returns: &'static str,
    pub example: &'static str,
}

pub fn all_functions() -> &'static [CFunc] {
    CFUNCS
}

pub fn headers() -> Vec<&'static str> {
    let mut h: Vec<&'static str> = CFUNCS.iter().map(|f| f.header).collect();
    h.sort();
    h.dedup();
    h
}

pub fn by_header(header: &str) -> Vec<&'static CFunc> {
    CFUNCS.iter().filter(|f| f.header == header).collect()
}

pub fn search(query: &str) -> Vec<&'static CFunc> {
    let q = query.to_lowercase();
    CFUNCS
        .iter()
        .filter(|f| {
            f.name.to_lowercase().contains(&q)
                || f.description.to_lowercase().contains(&q)
                || f.signature.to_lowercase().contains(&q)
        })
        .collect()
}

static CFUNCS: &[CFunc] = &[
    // ── stdio.h ──────────────────────────────────────────────────────────────
    CFunc {
        name: "printf",
        header: "stdio.h",
        signature: "int printf(const char *format, ...)",
        description: "Print formatted output to stdout. Format specifiers: %d (int), %f (double), %s (string), %c (char), %ld (long), %lf (double), %p (pointer).",
        returns: "Number of characters written, or negative on error.",
        example: "printf(\"Value: %d\\n\", 42);",
    },
    CFunc {
        name: "scanf",
        header: "stdio.h",
        signature: "int scanf(const char *format, ...)",
        description: "Read formatted input from stdin. Pass addresses of variables. %d reads int, %lf reads double, %s reads word (no spaces).",
        returns: "Number of items successfully matched and assigned.",
        example: "int n; scanf(\"%d\", &n);",
    },
    CFunc {
        name: "fprintf",
        header: "stdio.h",
        signature: "int fprintf(FILE *stream, const char *format, ...)",
        description: "Write formatted output to a file stream (or stderr for error messages).",
        returns: "Number of characters written, or negative on error.",
        example: "fprintf(stderr, \"Error: %s\\n\", msg);",
    },
    CFunc {
        name: "fscanf",
        header: "stdio.h",
        signature: "int fscanf(FILE *stream, const char *format, ...)",
        description: "Read formatted data from a file stream.",
        returns: "Number of items matched, or EOF on end-of-file or error.",
        example: "int x; fscanf(fp, \"%d\", &x);",
    },
    CFunc {
        name: "sprintf",
        header: "stdio.h",
        signature: "int sprintf(char *str, const char *format, ...)",
        description: "Write formatted output into a string buffer. Ensure buffer is large enough.",
        returns: "Number of characters written (not counting null terminator).",
        example: "char buf[64]; sprintf(buf, \"%d items\", count);",
    },
    CFunc {
        name: "snprintf",
        header: "stdio.h",
        signature: "int snprintf(char *str, size_t size, const char *format, ...)",
        description: "Safer sprintf — writes at most size-1 characters and always null-terminates.",
        returns: "Number of characters that would have been written if size were unlimited.",
        example: "snprintf(buf, sizeof(buf), \"%s: %d\", label, val);",
    },
    CFunc {
        name: "sscanf",
        header: "stdio.h",
        signature: "int sscanf(const char *str, const char *format, ...)",
        description: "Read formatted data from a string rather than stdin.",
        returns: "Number of items matched.",
        example: "int n; sscanf(\"42\", \"%d\", &n);",
    },
    CFunc {
        name: "fopen",
        header: "stdio.h",
        signature: "FILE *fopen(const char *filename, const char *mode)",
        description: "Open a file. Modes: \"r\" read, \"w\" write (truncate), \"a\" append, \"r+\" read+write, \"rb\" binary read, \"wb\" binary write.",
        returns: "FILE pointer, or NULL on failure.",
        example: "FILE *fp = fopen(\"data.txt\", \"r\");\nif (!fp) { perror(\"fopen\"); exit(1); }",
    },
    CFunc {
        name: "fclose",
        header: "stdio.h",
        signature: "int fclose(FILE *stream)",
        description: "Close an open file stream and flush its buffer. Always close files you open.",
        returns: "0 on success, EOF on error.",
        example: "fclose(fp);",
    },
    CFunc {
        name: "fgets",
        header: "stdio.h",
        signature: "char *fgets(char *str, int n, FILE *stream)",
        description: "Read at most n-1 characters from stream into str, stopping at newline or EOF. Includes the newline. Safer than gets().",
        returns: "str on success, NULL on EOF or error.",
        example: "char line[256]; fgets(line, sizeof(line), stdin);",
    },
    CFunc {
        name: "fputs",
        header: "stdio.h",
        signature: "int fputs(const char *str, FILE *stream)",
        description: "Write string str to stream (without adding a newline).",
        returns: "Non-negative on success, EOF on error.",
        example: "fputs(\"Hello\\n\", stdout);",
    },
    CFunc {
        name: "fread",
        header: "stdio.h",
        signature: "size_t fread(void *ptr, size_t size, size_t count, FILE *stream)",
        description: "Read count elements of size bytes each from stream into ptr. Used for binary files.",
        returns: "Number of elements successfully read (may be less than count on EOF/error).",
        example: "fread(buf, sizeof(int), 10, fp);",
    },
    CFunc {
        name: "fwrite",
        header: "stdio.h",
        signature: "size_t fwrite(const void *ptr, size_t size, size_t count, FILE *stream)",
        description: "Write count elements of size bytes each from ptr to stream.",
        returns: "Number of elements successfully written.",
        example: "fwrite(arr, sizeof(int), size, fp);",
    },
    CFunc {
        name: "feof",
        header: "stdio.h",
        signature: "int feof(FILE *stream)",
        description: "Test end-of-file indicator for stream. Note: returns non-zero AFTER a read fails at EOF, not before.",
        returns: "Non-zero if at end-of-file, 0 otherwise.",
        example: "while (!feof(fp)) { fgets(line, sizeof(line), fp); }",
    },
    CFunc {
        name: "fseek",
        header: "stdio.h",
        signature: "int fseek(FILE *stream, long offset, int whence)",
        description: "Move file position. whence: SEEK_SET (from start), SEEK_CUR (from current), SEEK_END (from end).",
        returns: "0 on success, non-zero on error.",
        example: "fseek(fp, 0, SEEK_SET); /* rewind */",
    },
    CFunc {
        name: "ftell",
        header: "stdio.h",
        signature: "long ftell(FILE *stream)",
        description: "Return current file position (byte offset from start).",
        returns: "Current position, or -1L on error.",
        example: "long pos = ftell(fp);",
    },
    CFunc {
        name: "rewind",
        header: "stdio.h",
        signature: "void rewind(FILE *stream)",
        description: "Reset file position to start and clear error/EOF indicators.",
        returns: "Nothing.",
        example: "rewind(fp);",
    },
    CFunc {
        name: "puts",
        header: "stdio.h",
        signature: "int puts(const char *str)",
        description: "Write str to stdout followed by a newline. Simpler than printf for plain strings.",
        returns: "Non-negative on success, EOF on error.",
        example: "puts(\"Hello, world!\");",
    },
    CFunc {
        name: "getchar",
        header: "stdio.h",
        signature: "int getchar(void)",
        description: "Read one character from stdin. Returns int to distinguish EOF (-1) from valid chars.",
        returns: "Character read as unsigned char cast to int, or EOF.",
        example: "int c = getchar();",
    },
    CFunc {
        name: "putchar",
        header: "stdio.h",
        signature: "int putchar(int c)",
        description: "Write one character to stdout.",
        returns: "Character written, or EOF on error.",
        example: "putchar('A');",
    },
    CFunc {
        name: "perror",
        header: "stdio.h",
        signature: "void perror(const char *str)",
        description: "Print str followed by a colon and the string for the current errno error. Useful after failed system calls.",
        returns: "Nothing.",
        example: "FILE *fp = fopen(\"x\", \"r\");\nif (!fp) { perror(\"fopen\"); exit(1); }",
    },
    CFunc {
        name: "remove",
        header: "stdio.h",
        signature: "int remove(const char *filename)",
        description: "Delete a file.",
        returns: "0 on success, non-zero on error.",
        example: "remove(\"temp.txt\");",
    },
    CFunc {
        name: "rename",
        header: "stdio.h",
        signature: "int rename(const char *old, const char *new)",
        description: "Rename or move a file.",
        returns: "0 on success, non-zero on error.",
        example: "rename(\"old.txt\", \"new.txt\");",
    },
    // ── stdlib.h ─────────────────────────────────────────────────────────────
    CFunc {
        name: "malloc",
        header: "stdlib.h",
        signature: "void *malloc(size_t size)",
        description: "Allocate size bytes of uninitialised heap memory. Always check for NULL return. Must be freed with free().",
        returns: "Pointer to allocated memory, or NULL on failure.",
        example: "int *arr = malloc(n * sizeof(int));\nif (!arr) { perror(\"malloc\"); exit(1); }",
    },
    CFunc {
        name: "calloc",
        header: "stdlib.h",
        signature: "void *calloc(size_t count, size_t size)",
        description: "Allocate count*size bytes, initialised to zero. Prefer over malloc when you need zero-initialisation.",
        returns: "Pointer to zeroed memory, or NULL on failure.",
        example: "int *arr = calloc(n, sizeof(int));",
    },
    CFunc {
        name: "realloc",
        header: "stdlib.h",
        signature: "void *realloc(void *ptr, size_t new_size)",
        description: "Resize a previously allocated block. May move it. If ptr is NULL, behaves like malloc. If new_size is 0, frees ptr.",
        returns: "New pointer (may differ from ptr), or NULL on failure (original ptr still valid).",
        example: "arr = realloc(arr, new_n * sizeof(int));",
    },
    CFunc {
        name: "free",
        header: "stdlib.h",
        signature: "void free(void *ptr)",
        description: "Release heap memory allocated by malloc/calloc/realloc. Passing NULL is safe (no-op). Never free the same pointer twice.",
        returns: "Nothing.",
        example: "free(arr); arr = NULL;",
    },
    CFunc {
        name: "exit",
        header: "stdlib.h",
        signature: "void exit(int status)",
        description: "Terminate the program. Flushes stdio buffers and runs atexit() handlers. Status 0 or EXIT_SUCCESS = normal, EXIT_FAILURE = error.",
        returns: "Does not return.",
        example: "if (error) exit(EXIT_FAILURE);",
    },
    CFunc {
        name: "atoi",
        header: "stdlib.h",
        signature: "int atoi(const char *str)",
        description: "Convert string to int. Does not detect errors — use strtol() for robust conversion.",
        returns: "Integer value, or 0 if conversion fails.",
        example: "int n = atoi(\"42\");",
    },
    CFunc {
        name: "atof",
        header: "stdlib.h",
        signature: "double atof(const char *str)",
        description: "Convert string to double. Does not detect errors — use strtod() for robust conversion.",
        returns: "Double value, or 0.0 if conversion fails.",
        example: "double d = atof(\"3.14\");",
    },
    CFunc {
        name: "strtol",
        header: "stdlib.h",
        signature: "long strtol(const char *str, char **endptr, int base)",
        description: "Robust string-to-long conversion. endptr points past the last character used; base is 10 for decimal, 0 for auto-detect.",
        returns: "Converted long value.",
        example: "char *end; long n = strtol(\"42\", &end, 10);",
    },
    CFunc {
        name: "strtod",
        header: "stdlib.h",
        signature: "double strtod(const char *str, char **endptr)",
        description: "Robust string-to-double conversion. *endptr points past last character used.",
        returns: "Converted double value.",
        example: "char *end; double d = strtod(\"3.14\", &end);",
    },
    CFunc {
        name: "rand",
        header: "stdlib.h",
        signature: "int rand(void)",
        description: "Generate a pseudo-random integer in [0, RAND_MAX]. Seed with srand() first.",
        returns: "Random integer in [0, RAND_MAX].",
        example: "srand(time(NULL)); int r = rand() % 100;",
    },
    CFunc {
        name: "srand",
        header: "stdlib.h",
        signature: "void srand(unsigned int seed)",
        description: "Seed the random number generator. Call once at program start. srand(time(NULL)) uses current time.",
        returns: "Nothing.",
        example: "srand((unsigned int)time(NULL));",
    },
    CFunc {
        name: "abs",
        header: "stdlib.h",
        signature: "int abs(int n)",
        description: "Absolute value of an int.",
        returns: "Absolute value of n.",
        example: "int a = abs(-5); /* 5 */",
    },
    CFunc {
        name: "qsort",
        header: "stdlib.h",
        signature: "void qsort(void *base, size_t count, size_t size, int (*compare)(const void *, const void *))",
        description: "Sort array in-place. compare(a,b) returns <0 if a<b, 0 if equal, >0 if a>b.",
        returns: "Nothing.",
        example: "int cmp(const void *a, const void *b) { return *(int*)a - *(int*)b; }\nqsort(arr, n, sizeof(int), cmp);",
    },
    CFunc {
        name: "bsearch",
        header: "stdlib.h",
        signature: "void *bsearch(const void *key, const void *base, size_t count, size_t size, int (*compare)(const void *, const void *))",
        description: "Binary search in sorted array. compare function same as qsort.",
        returns: "Pointer to matching element, or NULL if not found.",
        example: "int *p = bsearch(&target, arr, n, sizeof(int), cmp);",
    },
    // ── string.h ─────────────────────────────────────────────────────────────
    CFunc {
        name: "strlen",
        header: "string.h",
        signature: "size_t strlen(const char *s)",
        description: "Return length of string s, not counting the null terminator.",
        returns: "Number of characters before '\\0'.",
        example: "size_t len = strlen(\"hello\"); /* 5 */",
    },
    CFunc {
        name: "strcpy",
        header: "string.h",
        signature: "char *strcpy(char *dest, const char *src)",
        description: "Copy src into dest including null terminator. dest must be large enough. Prefer strncpy for safety.",
        returns: "dest.",
        example: "char buf[64]; strcpy(buf, \"hello\");",
    },
    CFunc {
        name: "strncpy",
        header: "string.h",
        signature: "char *strncpy(char *dest, const char *src, size_t n)",
        description: "Copy at most n characters from src to dest. If src is shorter, pads with '\\0'. If src is longer, result may not be null-terminated — add '\\0' manually.",
        returns: "dest.",
        example: "strncpy(buf, src, sizeof(buf) - 1); buf[sizeof(buf)-1] = '\\0';",
    },
    CFunc {
        name: "strcat",
        header: "string.h",
        signature: "char *strcat(char *dest, const char *src)",
        description: "Append src to end of dest. dest must have enough space for both strings.",
        returns: "dest.",
        example: "strcat(buf, \" world\");",
    },
    CFunc {
        name: "strncat",
        header: "string.h",
        signature: "char *strncat(char *dest, const char *src, size_t n)",
        description: "Append at most n characters of src to dest. Always null-terminates.",
        returns: "dest.",
        example: "strncat(buf, src, sizeof(buf) - strlen(buf) - 1);",
    },
    CFunc {
        name: "strcmp",
        header: "string.h",
        signature: "int strcmp(const char *s1, const char *s2)",
        description: "Compare two strings lexicographically.",
        returns: "<0 if s1 < s2, 0 if equal, >0 if s1 > s2.",
        example: "if (strcmp(s1, s2) == 0) { /* strings are equal */ }",
    },
    CFunc {
        name: "strncmp",
        header: "string.h",
        signature: "int strncmp(const char *s1, const char *s2, size_t n)",
        description: "Compare at most n characters of two strings.",
        returns: "<0, 0, or >0 as strcmp.",
        example: "strncmp(s1, s2, 3);",
    },
    CFunc {
        name: "strchr",
        header: "string.h",
        signature: "char *strchr(const char *s, int c)",
        description: "Find first occurrence of character c in string s.",
        returns: "Pointer to character, or NULL if not found.",
        example: "char *p = strchr(s, 'a');",
    },
    CFunc {
        name: "strrchr",
        header: "string.h",
        signature: "char *strrchr(const char *s, int c)",
        description: "Find last occurrence of character c in string s.",
        returns: "Pointer to last occurrence, or NULL if not found.",
        example: "char *last = strrchr(path, '/');",
    },
    CFunc {
        name: "strstr",
        header: "string.h",
        signature: "char *strstr(const char *haystack, const char *needle)",
        description: "Find first occurrence of substring needle in string haystack.",
        returns: "Pointer to start of needle in haystack, or NULL if not found.",
        example: "char *pos = strstr(text, \"hello\");",
    },
    CFunc {
        name: "strtok",
        header: "string.h",
        signature: "char *strtok(char *str, const char *delimiters)",
        description: "Split string into tokens. First call passes str; subsequent calls pass NULL. Modifies the string in-place.",
        returns: "Pointer to next token, or NULL when done.",
        example: "char *tok = strtok(line, \",\");\nwhile (tok) { printf(\"%s\\n\", tok); tok = strtok(NULL, \",\"); }",
    },
    CFunc {
        name: "memset",
        header: "string.h",
        signature: "void *memset(void *ptr, int value, size_t count)",
        description: "Fill count bytes of memory at ptr with value (interpreted as unsigned char). Useful for zeroing arrays.",
        returns: "ptr.",
        example: "memset(arr, 0, sizeof(arr));",
    },
    CFunc {
        name: "memcpy",
        header: "string.h",
        signature: "void *memcpy(void *dest, const void *src, size_t count)",
        description: "Copy count bytes from src to dest. Regions must not overlap — use memmove for overlapping regions.",
        returns: "dest.",
        example: "memcpy(dest_arr, src_arr, n * sizeof(int));",
    },
    CFunc {
        name: "memmove",
        header: "string.h",
        signature: "void *memmove(void *dest, const void *src, size_t count)",
        description: "Copy count bytes from src to dest, handling overlapping regions correctly.",
        returns: "dest.",
        example: "memmove(arr + 1, arr, (n-1) * sizeof(int));",
    },
    CFunc {
        name: "memcmp",
        header: "string.h",
        signature: "int memcmp(const void *s1, const void *s2, size_t count)",
        description: "Compare count bytes of memory at s1 and s2.",
        returns: "<0, 0, or >0.",
        example: "memcmp(a, b, sizeof(a));",
    },
    // ── math.h ───────────────────────────────────────────────────────────────
    CFunc {
        name: "sqrt",
        header: "math.h",
        signature: "double sqrt(double x)",
        description: "Square root of x. Compile with -lm on Linux.",
        returns: "Square root of x, or NaN if x < 0.",
        example: "double r = sqrt(2.0);",
    },
    CFunc {
        name: "pow",
        header: "math.h",
        signature: "double pow(double base, double exp)",
        description: "base raised to the power exp. For integer exponents prefer manual multiplication.",
        returns: "base^exp.",
        example: "double r = pow(2.0, 10.0); /* 1024.0 */",
    },
    CFunc {
        name: "fabs",
        header: "math.h",
        signature: "double fabs(double x)",
        description: "Absolute value of a double.",
        returns: "|x|.",
        example: "double a = fabs(-3.14);",
    },
    CFunc {
        name: "ceil",
        header: "math.h",
        signature: "double ceil(double x)",
        description: "Round x up to the nearest integer (toward +infinity).",
        returns: "Smallest integer >= x as double.",
        example: "ceil(1.2); /* 2.0 */",
    },
    CFunc {
        name: "floor",
        header: "math.h",
        signature: "double floor(double x)",
        description: "Round x down to the nearest integer (toward -infinity).",
        returns: "Largest integer <= x as double.",
        example: "floor(1.9); /* 1.0 */",
    },
    CFunc {
        name: "round",
        header: "math.h",
        signature: "double round(double x)",
        description: "Round x to the nearest integer, with halfway cases away from zero.",
        returns: "Nearest integer as double.",
        example: "round(1.5); /* 2.0 */",
    },
    CFunc {
        name: "fmod",
        header: "math.h",
        signature: "double fmod(double x, double y)",
        description: "Floating-point remainder of x/y (same sign as x).",
        returns: "x - n*y where n is the truncated quotient.",
        example: "fmod(5.5, 2.0); /* 1.5 */",
    },
    CFunc {
        name: "log",
        header: "math.h",
        signature: "double log(double x)",
        description: "Natural logarithm (base e) of x.",
        returns: "ln(x), or -infinity if x=0, NaN if x<0.",
        example: "double r = log(2.71828);",
    },
    CFunc {
        name: "log10",
        header: "math.h",
        signature: "double log10(double x)",
        description: "Base-10 logarithm of x.",
        returns: "log10(x).",
        example: "log10(100.0); /* 2.0 */",
    },
    CFunc {
        name: "sin",
        header: "math.h",
        signature: "double sin(double x)",
        description: "Sine of x in radians.",
        returns: "sin(x) in [-1, 1].",
        example: "sin(3.14159 / 2.0); /* ~1.0 */",
    },
    CFunc {
        name: "cos",
        header: "math.h",
        signature: "double cos(double x)",
        description: "Cosine of x in radians.",
        returns: "cos(x) in [-1, 1].",
        example: "cos(0.0); /* 1.0 */",
    },
    CFunc {
        name: "tan",
        header: "math.h",
        signature: "double tan(double x)",
        description: "Tangent of x in radians.",
        returns: "tan(x).",
        example: "tan(3.14159 / 4.0); /* ~1.0 */",
    },
    CFunc {
        name: "exp",
        header: "math.h",
        signature: "double exp(double x)",
        description: "e raised to the power x.",
        returns: "e^x.",
        example: "exp(1.0); /* ~2.71828 */",
    },
    // ── time.h ───────────────────────────────────────────────────────────────
    CFunc {
        name: "time",
        header: "time.h",
        signature: "time_t time(time_t *tloc)",
        description: "Return current calendar time as seconds since epoch (1 Jan 1970). Pass NULL if you don't need the pointer filled.",
        returns: "Current time as time_t, or -1 on error.",
        example: "time_t now = time(NULL);",
    },
    CFunc {
        name: "clock",
        header: "time.h",
        signature: "clock_t clock(void)",
        description: "Return processor time used by the program. Divide by CLOCKS_PER_SEC for seconds.",
        returns: "CPU time as clock_t.",
        example: "clock_t start = clock();\n/* ... */\ndouble elapsed = (double)(clock() - start) / CLOCKS_PER_SEC;",
    },
    CFunc {
        name: "difftime",
        header: "time.h",
        signature: "double difftime(time_t end, time_t start)",
        description: "Compute difference between two time_t values in seconds.",
        returns: "end - start as double.",
        example: "double secs = difftime(end_time, start_time);",
    },
    CFunc {
        name: "localtime",
        header: "time.h",
        signature: "struct tm *localtime(const time_t *timer)",
        description: "Convert time_t to broken-down local time (struct tm with tm_year, tm_mon, tm_mday, tm_hour, tm_min, tm_sec etc.).",
        returns: "Pointer to static struct tm (not thread-safe).",
        example: "time_t t = time(NULL);\nstruct tm *lt = localtime(&t);\nprintf(\"%d-%02d-%02d\\n\", lt->tm_year+1900, lt->tm_mon+1, lt->tm_mday);",
    },
    CFunc {
        name: "strftime",
        header: "time.h",
        signature: "size_t strftime(char *s, size_t max, const char *format, const struct tm *tm)",
        description: "Format broken-down time as string. Common formats: %Y year, %m month, %d day, %H hour, %M minute, %S second.",
        returns: "Number of characters placed in s (not counting '\\0'), or 0 if buffer too small.",
        example: "char buf[64];\nstrftime(buf, sizeof(buf), \"%Y-%m-%d %H:%M:%S\", localtime(&t));",
    },
    // ── ctype.h ──────────────────────────────────────────────────────────────
    CFunc {
        name: "isalpha",
        header: "ctype.h",
        signature: "int isalpha(int c)",
        description: "Test if c is an alphabetic letter (a-z or A-Z).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "if (isalpha(c)) { /* letter */ }",
    },
    CFunc {
        name: "isdigit",
        header: "ctype.h",
        signature: "int isdigit(int c)",
        description: "Test if c is a decimal digit (0-9).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "if (isdigit(c)) { /* digit */ }",
    },
    CFunc {
        name: "isalnum",
        header: "ctype.h",
        signature: "int isalnum(int c)",
        description: "Test if c is alphanumeric (letter or digit).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "if (isalnum(c)) { /* alphanumeric */ }",
    },
    CFunc {
        name: "isspace",
        header: "ctype.h",
        signature: "int isspace(int c)",
        description: "Test if c is a whitespace character (space, tab, newline, etc.).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "while (isspace(*p)) p++; /* skip whitespace */",
    },
    CFunc {
        name: "isupper",
        header: "ctype.h",
        signature: "int isupper(int c)",
        description: "Test if c is an uppercase letter (A-Z).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "if (isupper(c)) { /* uppercase */ }",
    },
    CFunc {
        name: "islower",
        header: "ctype.h",
        signature: "int islower(int c)",
        description: "Test if c is a lowercase letter (a-z).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "if (islower(c)) { /* lowercase */ }",
    },
    CFunc {
        name: "toupper",
        header: "ctype.h",
        signature: "int toupper(int c)",
        description: "Convert lowercase letter to uppercase. Non-letter characters unchanged.",
        returns: "Uppercase equivalent, or c unchanged.",
        example: "char u = (char)toupper('a'); /* 'A' */",
    },
    CFunc {
        name: "tolower",
        header: "ctype.h",
        signature: "int tolower(int c)",
        description: "Convert uppercase letter to lowercase. Non-letter characters unchanged.",
        returns: "Lowercase equivalent, or c unchanged.",
        example: "char l = (char)tolower('A'); /* 'a' */",
    },
    CFunc {
        name: "ispunct",
        header: "ctype.h",
        signature: "int ispunct(int c)",
        description: "Test if c is a punctuation character (printable but not alphanumeric or space).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "if (ispunct(c)) { /* punctuation */ }",
    },
    CFunc {
        name: "isprint",
        header: "ctype.h",
        signature: "int isprint(int c)",
        description: "Test if c is a printable character (including space).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "if (isprint(c)) putchar(c);",
    },
    CFunc {
        name: "isxdigit",
        header: "ctype.h",
        signature: "int isxdigit(int c)",
        description: "Test if c is a hexadecimal digit (0-9, a-f, A-F).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "if (isxdigit(c)) { /* hex digit */ }",
    },
    CFunc {
        name: "iscntrl",
        header: "ctype.h",
        signature: "int iscntrl(int c)",
        description: "Test if c is a control character (ASCII 0-31 and 127).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "if (iscntrl(c)) { /* control char */ }",
    },
    // ── stdio.h extras ───────────────────────────────────────────────────────
    CFunc {
        name: "fgetc",
        header: "stdio.h",
        signature: "int fgetc(FILE *stream)",
        description: "Read one character from stream. Returns int to represent both valid chars and EOF (-1).",
        returns: "Character as unsigned char cast to int, or EOF on end-of-file or error.",
        example: "int c;\nwhile ((c = fgetc(fp)) != EOF) { putchar(c); }",
    },
    CFunc {
        name: "fputc",
        header: "stdio.h",
        signature: "int fputc(int c, FILE *stream)",
        description: "Write character c to stream.",
        returns: "Character written, or EOF on error.",
        example: "fputc('A', fp);",
    },
    CFunc {
        name: "ungetc",
        header: "stdio.h",
        signature: "int ungetc(int c, FILE *stream)",
        description: "Push character c back onto stream so the next read returns it. Only one character of pushback is guaranteed.",
        returns: "c on success, EOF on error.",
        example: "int c = fgetc(fp);\nif (!isdigit(c)) ungetc(c, fp); /* put it back */",
    },
    CFunc {
        name: "fflush",
        header: "stdio.h",
        signature: "int fflush(FILE *stream)",
        description: "Flush output buffer of stream to the underlying file. Pass NULL to flush all open output streams. Useful before fork() or after printf without newline.",
        returns: "0 on success, EOF on error.",
        example: "printf(\"Enter value: \");\nfflush(stdout);",
    },
    CFunc {
        name: "ferror",
        header: "stdio.h",
        signature: "int ferror(FILE *stream)",
        description: "Test whether an error occurred on stream. Error indicator persists until cleared by clearerr() or rewind().",
        returns: "Non-zero if error indicator is set, 0 otherwise.",
        example: "if (ferror(fp)) { fprintf(stderr, \"Read error\\n\"); }",
    },
    CFunc {
        name: "clearerr",
        header: "stdio.h",
        signature: "void clearerr(FILE *stream)",
        description: "Clear the error and end-of-file indicators for stream.",
        returns: "Nothing.",
        example: "clearerr(fp); /* reset after handling error */",
    },
    // ── stdlib.h extras ──────────────────────────────────────────────────────
    CFunc {
        name: "abort",
        header: "stdlib.h",
        signature: "void abort(void)",
        description: "Cause abnormal program termination (SIGABRT). Does NOT flush stdio buffers or run atexit() handlers. Use for unrecoverable internal errors.",
        returns: "Does not return.",
        example: "if (ptr == NULL) { fprintf(stderr, \"fatal\\n\"); abort(); }",
    },
    CFunc {
        name: "atexit",
        header: "stdlib.h",
        signature: "int atexit(void (*func)(void))",
        description: "Register func to be called at normal program exit (via exit() or return from main). Multiple functions can be registered; they run in reverse order.",
        returns: "0 on success, non-zero on failure.",
        example: "void cleanup(void) { printf(\"bye\\n\"); }\natexit(cleanup);",
    },
    CFunc {
        name: "labs",
        header: "stdlib.h",
        signature: "long labs(long n)",
        description: "Absolute value of a long integer. Use llabs() for long long.",
        returns: "Absolute value of n.",
        example: "long a = labs(-123456L);",
    },
    CFunc {
        name: "div",
        header: "stdlib.h",
        signature: "div_t div(int numerator, int denominator)",
        description: "Compute quotient and remainder in one call. Returns a div_t struct with .quot (quotient) and .rem (remainder).",
        returns: "div_t with .quot and .rem.",
        example: "div_t r = div(17, 5); /* r.quot=3, r.rem=2 */",
    },
    CFunc {
        name: "system",
        header: "stdlib.h",
        signature: "int system(const char *command)",
        description: "Execute a shell command. Blocks until command completes. Pass NULL to check if a shell is available.",
        returns: "Exit status of command, or -1 on error.",
        example: "system(\"clear\"); /* clear terminal */",
    },
    CFunc {
        name: "getenv",
        header: "stdlib.h",
        signature: "char *getenv(const char *name)",
        description: "Retrieve value of environment variable name. Do not modify the returned string.",
        returns: "Pointer to value string, or NULL if not found.",
        example: "char *home = getenv(\"HOME\");\nif (home) printf(\"Home: %s\\n\", home);",
    },
    CFunc {
        name: "strtoul",
        header: "stdlib.h",
        signature: "unsigned long strtoul(const char *str, char **endptr, int base)",
        description: "Robust string-to-unsigned-long conversion. Like strtol but for unsigned values.",
        returns: "Converted unsigned long value.",
        example: "unsigned long n = strtoul(\"0xFF\", NULL, 16);",
    },
    // ── string.h extras ──────────────────────────────────────────────────────
    CFunc {
        name: "strerror",
        header: "string.h",
        signature: "char *strerror(int errnum)",
        description: "Return a human-readable string describing the error code errnum (from errno). Do not modify the returned string.",
        returns: "Pointer to static error message string.",
        example: "#include <errno.h>\nprintf(\"Error: %s\\n\", strerror(errno));",
    },
    CFunc {
        name: "strdup",
        header: "string.h",
        signature: "char *strdup(const char *s)",
        description: "POSIX. Allocate a new string that is a copy of s. The caller must free() the result.",
        returns: "Pointer to newly allocated copy, or NULL on allocation failure.",
        example: "char *copy = strdup(original);\nif (!copy) { perror(\"strdup\"); exit(1); }\n/* ... */\nfree(copy);",
    },
    CFunc {
        name: "memchr",
        header: "string.h",
        signature: "void *memchr(const void *ptr, int c, size_t count)",
        description: "Search for byte value c in the first count bytes of memory at ptr.",
        returns: "Pointer to first matching byte, or NULL if not found.",
        example: "char *p = memchr(buf, '\\n', sizeof(buf));",
    },
    // ── math.h extras ────────────────────────────────────────────────────────
    CFunc {
        name: "atan",
        header: "math.h",
        signature: "double atan(double x)",
        description: "Arc tangent of x in radians. Returns value in [-π/2, π/2]. Compile with -lm.",
        returns: "atan(x) in radians.",
        example: "double angle = atan(1.0); /* π/4 */",
    },
    CFunc {
        name: "atan2",
        header: "math.h",
        signature: "double atan2(double y, double x)",
        description: "Arc tangent of y/x, using signs to determine quadrant. Returns value in (-π, π]. Handles x=0 correctly. Compile with -lm.",
        returns: "atan(y/x) in [-π, π].",
        example: "double angle = atan2(1.0, 1.0); /* π/4 */",
    },
    CFunc {
        name: "asin",
        header: "math.h",
        signature: "double asin(double x)",
        description: "Arc sine of x. x must be in [-1, 1]. Compile with -lm.",
        returns: "asin(x) in [-π/2, π/2], or NaN if |x| > 1.",
        example: "double r = asin(0.5); /* π/6 */",
    },
    CFunc {
        name: "acos",
        header: "math.h",
        signature: "double acos(double x)",
        description: "Arc cosine of x. x must be in [-1, 1]. Compile with -lm.",
        returns: "acos(x) in [0, π], or NaN if |x| > 1.",
        example: "double r = acos(0.0); /* π/2 */",
    },
    CFunc {
        name: "hypot",
        header: "math.h",
        signature: "double hypot(double x, double y)",
        description: "Euclidean distance sqrt(x*x + y*y) without intermediate overflow. Compile with -lm.",
        returns: "sqrt(x² + y²).",
        example: "double dist = hypot(3.0, 4.0); /* 5.0 */",
    },
    CFunc {
        name: "modf",
        header: "math.h",
        signature: "double modf(double x, double *iptr)",
        description: "Split x into integer and fractional parts; stores integer part in *iptr. Both parts have the same sign as x.",
        returns: "Signed fractional part.",
        example: "double intpart, frac = modf(3.75, &intpart); /* frac=0.75, intpart=3.0 */",
    },
    // ── assert.h ─────────────────────────────────────────────────────────────
    CFunc {
        name: "assert",
        header: "assert.h",
        signature: "void assert(int expression)",
        description: "Macro that aborts the program with a diagnostic message if expression is false (0). Disabled when NDEBUG is defined. Use for preconditions and invariants during development.",
        returns: "Nothing (aborts if expression is false).",
        example: "assert(ptr != NULL);\nassert(n > 0 && n < MAX);",
    },
    // ── stdarg.h ─────────────────────────────────────────────────────────────
    CFunc {
        name: "va_start",
        header: "stdarg.h",
        signature: "void va_start(va_list ap, last_fixed)",
        description: "Macro to initialise ap (a va_list) for traversing variadic arguments. last_fixed is the last named parameter before '...'. Must be paired with va_end.",
        returns: "Nothing.",
        example: "void my_printf(const char *fmt, ...) {\n    va_list ap;\n    va_start(ap, fmt);\n    vprintf(fmt, ap);\n    va_end(ap);\n}",
    },
    CFunc {
        name: "va_arg",
        header: "stdarg.h",
        signature: "type va_arg(va_list ap, type)",
        description: "Macro to retrieve next variadic argument of the given type from ap. Calling with the wrong type is undefined behaviour.",
        returns: "Next argument as the specified type.",
        example: "int n = va_arg(ap, int);\nchar *s = va_arg(ap, char *);",
    },
    CFunc {
        name: "va_end",
        header: "stdarg.h",
        signature: "void va_end(va_list ap)",
        description: "Macro to clean up a va_list after processing. Must be called before the function returns.",
        returns: "Nothing.",
        example: "va_end(ap);",
    },
    // ── errno.h ──────────────────────────────────────────────────────────────
    CFunc {
        name: "errno",
        header: "errno.h",
        signature: "extern int errno",
        description: "Global integer set by system calls and library functions on error. Check immediately after a failed call before calling anything else. Common values: ENOENT (no such file), EINVAL (invalid argument), ENOMEM (out of memory), EACCES (permission denied).",
        returns: "N/A — not a function.",
        example: "#include <errno.h>\n#include <string.h>\nFILE *fp = fopen(\"x\", \"r\");\nif (!fp) { fprintf(stderr, \"Error: %s\\n\", strerror(errno)); }",
    },
    // ── signal.h ─────────────────────────────────────────────────────────────
    CFunc {
        name: "signal",
        header: "signal.h",
        signature: "void (*signal(int signum, void (*handler)(int)))(int)",
        description: "Set handler for signal signum. handler can be SIG_DFL (default), SIG_IGN (ignore), or a function pointer. Common signals: SIGINT (Ctrl+C), SIGTERM, SIGSEGV, SIGFPE.",
        returns: "Previous handler, or SIG_ERR on error.",
        example: "void handler(int sig) { printf(\"Caught %d\\n\", sig); }\nsignal(SIGINT, handler);",
    },
    CFunc {
        name: "raise",
        header: "signal.h",
        signature: "int raise(int signum)",
        description: "Send signal signum to the calling process.",
        returns: "0 on success, non-zero on failure.",
        example: "raise(SIGTERM);",
    },
    // ── setjmp.h ─────────────────────────────────────────────────────────────
    CFunc {
        name: "setjmp",
        header: "setjmp.h",
        signature: "int setjmp(jmp_buf env)",
        description: "Save the current execution context into env. Returns 0 on first call; returns the value passed to longjmp on jump. Used for non-local error handling — use sparingly.",
        returns: "0 on initial call, non-zero value on longjmp return.",
        example: "jmp_buf env;\nif (setjmp(env) != 0) { printf(\"jumped!\\n\"); }",
    },
    CFunc {
        name: "longjmp",
        header: "setjmp.h",
        signature: "void longjmp(jmp_buf env, int val)",
        description: "Restore execution context saved by setjmp. val is returned by setjmp at the destination (if 0 is passed, setjmp returns 1). Unwinds the stack without calling destructors — use with care.",
        returns: "Does not return.",
        example: "longjmp(env, 1); /* jump back to setjmp */",
    },
    // ── stdlib.h macros ──────────────────────────────────────────────────────
    CFunc {
        name: "EXIT_SUCCESS",
        header: "stdlib.h",
        signature: "#define EXIT_SUCCESS 0",
        description: "Macro indicating successful program termination. Pass to exit() or return from main(). Portable — prefer over bare 0.",
        returns: "N/A — macro constant (value 0).",
        example: "return EXIT_SUCCESS;",
    },
    CFunc {
        name: "EXIT_FAILURE",
        header: "stdlib.h",
        signature: "#define EXIT_FAILURE 1",
        description: "Macro indicating unsuccessful program termination. Pass to exit() or return from main() when an error occurred.",
        returns: "N/A — macro constant (typically 1).",
        example: "if (!fp) { perror(\"fopen\"); exit(EXIT_FAILURE); }",
    },
    CFunc {
        name: "NULL",
        header: "stdlib.h",
        signature: "#define NULL ((void *)0)",
        description: "Null pointer constant. Defined in stddef.h and re-exported by stdio.h, stdlib.h, string.h, and others. Use to initialise pointers and as a sentinel value. Comparing a pointer to NULL tests if it is uninitialised or invalid.",
        returns: "N/A — macro constant.",
        example: "int *p = NULL;\nif (p == NULL) { /* not yet allocated */ }",
    },
    CFunc {
        name: "RAND_MAX",
        header: "stdlib.h",
        signature: "#define RAND_MAX /* implementation-defined, at least 32767 */",
        description: "Maximum value returned by rand(). Use to scale random values: (double)rand() / RAND_MAX gives a value in [0.0, 1.0].",
        returns: "N/A — macro constant.",
        example: "int die = rand() % 6 + 1;\ndouble frac = (double)rand() / RAND_MAX;",
    },
    // ── stdio.h macros ───────────────────────────────────────────────────────
    CFunc {
        name: "EOF",
        header: "stdio.h",
        signature: "#define EOF (-1)",
        description: "End-of-file indicator returned by character I/O functions (fgetc, getchar, etc.) and scanf family when input is exhausted or an error occurs. Always store in int, not char, so it can be distinguished from valid character values.",
        returns: "N/A — macro constant (value -1).",
        example: "int c;\nwhile ((c = fgetc(fp)) != EOF) { putchar(c); }",
    },
    CFunc {
        name: "BUFSIZ",
        header: "stdio.h",
        signature: "#define BUFSIZ /* implementation-defined, typically 512 or 8192 */",
        description: "Default buffer size used by setbuf(). Also a reasonable size for general-purpose I/O buffers.",
        returns: "N/A — macro constant.",
        example: "char buf[BUFSIZ];\nfgets(buf, sizeof(buf), stdin);",
    },
    CFunc {
        name: "FILENAME_MAX",
        header: "stdio.h",
        signature: "#define FILENAME_MAX /* implementation-defined */",
        description: "Maximum length of a filename string the implementation guarantees can be opened. Use as buffer size for path strings.",
        returns: "N/A — macro constant.",
        example: "char path[FILENAME_MAX];\nsnprintf(path, sizeof(path), \"%s/%s\", dir, file);",
    },
    CFunc {
        name: "stderr",
        header: "stdio.h",
        signature: "#define stderr /* FILE * pointing to standard error */",
        description: "Pre-opened FILE stream for error output. Not buffered by default so messages appear immediately. Use for diagnostics and errors, never for normal output.",
        returns: "N/A — macro (FILE *).",
        example: "fprintf(stderr, \"Error: file not found\\n\");",
    },
    CFunc {
        name: "stdin",
        header: "stdio.h",
        signature: "#define stdin /* FILE * pointing to standard input */",
        description: "Pre-opened FILE stream for standard input (keyboard by default). Can be redirected. Pass to fgets, fscanf, fgetc etc. as the stream argument.",
        returns: "N/A — macro (FILE *).",
        example: "fgets(line, sizeof(line), stdin);",
    },
    CFunc {
        name: "stdout",
        header: "stdio.h",
        signature: "#define stdout /* FILE * pointing to standard output */",
        description: "Pre-opened FILE stream for standard output. Line-buffered when connected to a terminal. Pass to fprintf, fputs etc. when you need an explicit stream.",
        returns: "N/A — macro (FILE *).",
        example: "fputs(\"Hello\\n\", stdout);\nfflush(stdout);",
    },
    // ── limits.h macros ──────────────────────────────────────────────────────
    CFunc {
        name: "INT_MAX",
        header: "limits.h",
        signature: "#define INT_MAX 2147483647",
        description: "Maximum value of a signed int (2^31 − 1 on 32-bit int platforms). Use to detect overflow or initialise a minimum-search variable.",
        returns: "N/A — macro constant.",
        example: "int min = INT_MAX;\nfor (int i = 0; i < n; i++) if (arr[i] < min) min = arr[i];",
    },
    CFunc {
        name: "INT_MIN",
        header: "limits.h",
        signature: "#define INT_MIN (-2147483648)",
        description: "Minimum value of a signed int (−2^31 on 32-bit int platforms).",
        returns: "N/A — macro constant.",
        example: "int max = INT_MIN;\nfor (int i = 0; i < n; i++) if (arr[i] > max) max = arr[i];",
    },
    CFunc {
        name: "UINT_MAX",
        header: "limits.h",
        signature: "#define UINT_MAX 4294967295U",
        description: "Maximum value of an unsigned int (2^32 − 1 on 32-bit platforms).",
        returns: "N/A — macro constant.",
        example: "unsigned int u = UINT_MAX; /* wraps to 0 on increment */",
    },
    CFunc {
        name: "LONG_MAX",
        header: "limits.h",
        signature: "#define LONG_MAX 9223372036854775807L",
        description: "Maximum value of a signed long (2^63 − 1 on 64-bit platforms, 2^31 − 1 on 32-bit).",
        returns: "N/A — macro constant.",
        example: "long big = LONG_MAX;",
    },
    CFunc {
        name: "LONG_MIN",
        header: "limits.h",
        signature: "#define LONG_MIN (-LONG_MAX - 1L)",
        description: "Minimum value of a signed long.",
        returns: "N/A — macro constant.",
        example: "long small = LONG_MIN;",
    },
    CFunc {
        name: "CHAR_MAX",
        header: "limits.h",
        signature: "#define CHAR_MAX 127",
        description: "Maximum value of a char (127 if char is signed, 255 if unsigned — implementation-defined).",
        returns: "N/A — macro constant.",
        example: "if (c <= CHAR_MAX) { /* valid char value */ }",
    },
    CFunc {
        name: "CHAR_MIN",
        header: "limits.h",
        signature: "#define CHAR_MIN (-128)",
        description: "Minimum value of a char (−128 if signed, 0 if unsigned).",
        returns: "N/A — macro constant.",
        example: "/* Use to check char signedness */",
    },
    CFunc {
        name: "SHRT_MAX",
        header: "limits.h",
        signature: "#define SHRT_MAX 32767",
        description: "Maximum value of a signed short int (2^15 − 1).",
        returns: "N/A — macro constant.",
        example: "short s = SHRT_MAX;",
    },
    // ── float.h macros ───────────────────────────────────────────────────────
    CFunc {
        name: "DBL_MAX",
        header: "float.h",
        signature: "#define DBL_MAX 1.7976931348623157e+308",
        description: "Maximum finite value of a double. Use to initialise a minimum-search or check for near-overflow.",
        returns: "N/A — macro constant.",
        example: "double min = DBL_MAX;\nfor (int i = 0; i < n; i++) if (arr[i] < min) min = arr[i];",
    },
    CFunc {
        name: "DBL_MIN",
        header: "float.h",
        signature: "#define DBL_MIN 2.2250738585072014e-308",
        description: "Smallest positive normalised double (NOT most negative). For the smallest representable value use -DBL_MAX.",
        returns: "N/A — macro constant.",
        example: "/* Smallest positive normal double */\ndouble tiny = DBL_MIN;",
    },
    CFunc {
        name: "DBL_EPSILON",
        header: "float.h",
        signature: "#define DBL_EPSILON 2.2204460492503131e-16",
        description: "Smallest double such that 1.0 + DBL_EPSILON != 1.0. Use for floating-point equality comparisons: fabs(a - b) < DBL_EPSILON * fabs(a).",
        returns: "N/A — macro constant.",
        example: "if (fabs(a - b) < DBL_EPSILON) { /* treat as equal */ }",
    },
    CFunc {
        name: "FLT_MAX",
        header: "float.h",
        signature: "#define FLT_MAX 3.4028235e+38F",
        description: "Maximum finite value of a float.",
        returns: "N/A — macro constant.",
        example: "float f = FLT_MAX;",
    },
    CFunc {
        name: "FLT_EPSILON",
        header: "float.h",
        signature: "#define FLT_EPSILON 1.1920929e-07F",
        description: "Machine epsilon for float — smallest value such that 1.0f + FLT_EPSILON != 1.0f.",
        returns: "N/A — macro constant.",
        example: "if (fabsf(a - b) < FLT_EPSILON) { /* floats equal */ }",
    },
    // ── math.h macros ────────────────────────────────────────────────────────
    CFunc {
        name: "M_PI",
        header: "math.h",
        signature: "#define M_PI 3.14159265358979323846",
        description: "POSIX extension (not strict C99/C11). π to full double precision. Define _USE_MATH_DEFINES on Windows before including math.h, or define your own if needed.",
        returns: "N/A — macro constant.",
        example: "double circumference = 2.0 * M_PI * radius;",
    },
    CFunc {
        name: "M_E",
        header: "math.h",
        signature: "#define M_E 2.71828182845904523536",
        description: "POSIX extension. Euler's number e to full double precision.",
        returns: "N/A — macro constant.",
        example: "double r = pow(M_E, 1.0); /* same as exp(1.0) */",
    },
    CFunc {
        name: "HUGE_VAL",
        header: "math.h",
        signature: "#define HUGE_VAL /* positive infinity or largest double */",
        description: "Returned by math functions on overflow. On IEEE 754 platforms this is positive infinity. Check with isinf() from math.h.",
        returns: "N/A — macro constant.",
        example: "if (result == HUGE_VAL) { fprintf(stderr, \"overflow\\n\"); }",
    },
    CFunc {
        name: "INFINITY",
        header: "math.h",
        signature: "#define INFINITY /* IEEE 754 positive infinity */",
        description: "Positive infinity (C99). Arithmetic: x / INFINITY == 0.0, INFINITY + x == INFINITY. Use isinf() to test. Negate for -INFINITY.",
        returns: "N/A — macro constant.",
        example: "double inf = INFINITY;\ndouble neg_inf = -INFINITY;",
    },
    CFunc {
        name: "NAN",
        header: "math.h",
        signature: "#define NAN /* IEEE 754 not-a-number */",
        description: "Not-a-Number constant (C99). NAN != NAN is always true — use isnan() to test. Produced by 0.0/0.0, sqrt(-1), etc.",
        returns: "N/A — macro constant.",
        example: "double bad = NAN;\nif (isnan(bad)) { printf(\"not a number\\n\"); }",
    },
    // ── signal.h macros ──────────────────────────────────────────────────────
    CFunc {
        name: "SIGINT",
        header: "signal.h",
        signature: "#define SIGINT 2",
        description: "Signal sent when user presses Ctrl+C. Default action: terminate. Commonly caught to allow graceful cleanup.",
        returns: "N/A — macro constant.",
        example: "signal(SIGINT, handler); /* catch Ctrl+C */",
    },
    CFunc {
        name: "SIGTERM",
        header: "signal.h",
        signature: "#define SIGTERM 15",
        description: "Termination request signal (sent by kill command by default). Default action: terminate. Catch to save state before exiting.",
        returns: "N/A — macro constant.",
        example: "signal(SIGTERM, cleanup_and_exit);",
    },
    CFunc {
        name: "SIGSEGV",
        header: "signal.h",
        signature: "#define SIGSEGV 11",
        description: "Segmentation fault — invalid memory access (null pointer dereference, out-of-bounds, etc.). Default action: terminate with core dump. Cannot reliably recover from this.",
        returns: "N/A — macro constant.",
        example: "signal(SIGSEGV, handler); /* log crash info */",
    },
    CFunc {
        name: "SIGFPE",
        header: "signal.h",
        signature: "#define SIGFPE 8",
        description: "Floating-point exception — integer divide-by-zero, overflow, etc. Default action: terminate with core dump.",
        returns: "N/A — macro constant.",
        example: "signal(SIGFPE, handler);",
    },
    CFunc {
        name: "SIGABRT",
        header: "signal.h",
        signature: "#define SIGABRT 6",
        description: "Abort signal raised by abort(). Also raised by assert() failure and internal library errors.",
        returns: "N/A — macro constant.",
        example: "signal(SIGABRT, handler);",
    },
    CFunc {
        name: "SIG_DFL",
        header: "signal.h",
        signature: "#define SIG_DFL ((void (*)(int))0)",
        description: "Pass to signal() to restore the default handler for a signal.",
        returns: "N/A — macro constant.",
        example: "signal(SIGINT, SIG_DFL); /* restore default Ctrl+C behaviour */",
    },
    CFunc {
        name: "SIG_IGN",
        header: "signal.h",
        signature: "#define SIG_IGN ((void (*)(int))1)",
        description: "Pass to signal() to ignore a signal entirely.",
        returns: "N/A — macro constant.",
        example: "signal(SIGPIPE, SIG_IGN); /* ignore broken pipe */",
    },
    // ── errno.h macros ───────────────────────────────────────────────────────
    CFunc {
        name: "ENOENT",
        header: "errno.h",
        signature: "#define ENOENT 2",
        description: "No such file or directory. Set by fopen, open, stat etc. when the path does not exist.",
        returns: "N/A — error code constant.",
        example: "if (errno == ENOENT) { printf(\"File not found\\n\"); }",
    },
    CFunc {
        name: "EINVAL",
        header: "errno.h",
        signature: "#define EINVAL 22",
        description: "Invalid argument. Set when a parameter value is out of range or otherwise invalid.",
        returns: "N/A — error code constant.",
        example: "if (errno == EINVAL) { printf(\"Bad argument\\n\"); }",
    },
    CFunc {
        name: "ENOMEM",
        header: "errno.h",
        signature: "#define ENOMEM 12",
        description: "Out of memory. Set by malloc/calloc/realloc when heap allocation fails.",
        returns: "N/A — error code constant.",
        example: "int *p = malloc(n * sizeof(int));\nif (!p) { perror(\"malloc\"); exit(EXIT_FAILURE); }",
    },
    CFunc {
        name: "EACCES",
        header: "errno.h",
        signature: "#define EACCES 13",
        description: "Permission denied. Set when process lacks permission to open/read/write a file.",
        returns: "N/A — error code constant.",
        example: "if (errno == EACCES) { printf(\"Permission denied\\n\"); }",
    },
    CFunc {
        name: "ERANGE",
        header: "errno.h",
        signature: "#define ERANGE 34",
        description: "Result out of range. Set by strtol/strtod when the converted value overflows, and by math functions on overflow.",
        returns: "N/A — error code constant.",
        example: "errno = 0;\nlong n = strtol(str, NULL, 10);\nif (errno == ERANGE) { printf(\"Overflow\\n\"); }",
    },
    CFunc {
        name: "EEXIST",
        header: "errno.h",
        signature: "#define EEXIST 17",
        description: "File already exists. Set by functions that create files when the target already exists.",
        returns: "N/A — error code constant.",
        example: "if (errno == EEXIST) { printf(\"File already exists\\n\"); }",
    },
    // ── time.h macros ────────────────────────────────────────────────────────
    CFunc {
        name: "CLOCKS_PER_SEC",
        header: "time.h",
        signature: "#define CLOCKS_PER_SEC 1000000",
        description: "Number of clock_t ticks per second. Divide (clock() - start) by this to get elapsed CPU seconds. Value is implementation-defined (typically 1,000,000 on POSIX).",
        returns: "N/A — macro constant.",
        example: "clock_t start = clock();\n/* work */\ndouble sec = (double)(clock() - start) / CLOCKS_PER_SEC;\nprintf(\"Elapsed: %.3f s\\n\", sec);",
    },
    // ── stdbool.h ────────────────────────────────────────────────────────────
    CFunc {
        name: "bool",
        header: "stdbool.h",
        signature: "#define bool _Bool",
        description: "Boolean type alias (C99). Include <stdbool.h> to use bool, true, and false instead of int. Stored as 0 or 1. Useful for clarity in flag variables and function return types.",
        returns: "N/A — type macro.",
        example: "#include <stdbool.h>\nbool found = false;\nfor (int i = 0; i < n; i++) {\n    if (arr[i] == target) { found = true; break; }\n}",
    },
    CFunc {
        name: "true",
        header: "stdbool.h",
        signature: "#define true 1",
        description: "Boolean true constant (C99, requires <stdbool.h>). Numerically equal to 1.",
        returns: "N/A — macro constant.",
        example: "bool running = true;\nwhile (running) { /* ... */ }",
    },
    CFunc {
        name: "false",
        header: "stdbool.h",
        signature: "#define false 0",
        description: "Boolean false constant (C99, requires <stdbool.h>). Numerically equal to 0.",
        returns: "N/A — macro constant.",
        example: "bool done = false;\nif (condition) done = true;",
    },
    // ── stdint.h ─────────────────────────────────────────────────────────────
    CFunc {
        name: "int8_t",
        header: "stdint.h",
        signature: "typedef signed char int8_t",
        description: "Exact-width signed 8-bit integer (C99). Range: −128 to 127. Use exact-width types when bit layout matters (file formats, protocols, hardware registers).",
        returns: "N/A — typedef.",
        example: "int8_t byte = -1;",
    },
    CFunc {
        name: "uint8_t",
        header: "stdint.h",
        signature: "typedef unsigned char uint8_t",
        description: "Exact-width unsigned 8-bit integer. Range: 0 to 255. Common for byte arrays and pixel data.",
        returns: "N/A — typedef.",
        example: "uint8_t buf[256];\nbuf[0] = 0xFF;",
    },
    CFunc {
        name: "int16_t",
        header: "stdint.h",
        signature: "typedef signed short int16_t",
        description: "Exact-width signed 16-bit integer. Range: −32768 to 32767.",
        returns: "N/A — typedef.",
        example: "int16_t sample = -1000;",
    },
    CFunc {
        name: "uint16_t",
        header: "stdint.h",
        signature: "typedef unsigned short uint16_t",
        description: "Exact-width unsigned 16-bit integer. Range: 0 to 65535.",
        returns: "N/A — typedef.",
        example: "uint16_t port = 8080;",
    },
    CFunc {
        name: "int32_t",
        header: "stdint.h",
        signature: "typedef signed int int32_t",
        description: "Exact-width signed 32-bit integer. Range: −2,147,483,648 to 2,147,483,647. Use when you need exactly 32 bits regardless of platform.",
        returns: "N/A — typedef.",
        example: "int32_t count = 0;",
    },
    CFunc {
        name: "uint32_t",
        header: "stdint.h",
        signature: "typedef unsigned int uint32_t",
        description: "Exact-width unsigned 32-bit integer. Range: 0 to 4,294,967,295.",
        returns: "N/A — typedef.",
        example: "uint32_t flags = 0xDEADBEEF;",
    },
    CFunc {
        name: "int64_t",
        header: "stdint.h",
        signature: "typedef signed long long int64_t",
        description: "Exact-width signed 64-bit integer. Range: −9.2×10^18 to 9.2×10^18. Use for large counters, file sizes, timestamps.",
        returns: "N/A — typedef.",
        example: "int64_t file_size = 1LL << 40; /* 1 TiB */",
    },
    CFunc {
        name: "uint64_t",
        header: "stdint.h",
        signature: "typedef unsigned long long uint64_t",
        description: "Exact-width unsigned 64-bit integer. Range: 0 to 1.8×10^19.",
        returns: "N/A — typedef.",
        example: "uint64_t mask = 0xFFFFFFFFFFFFFFFFULL;",
    },
    CFunc {
        name: "SIZE_MAX",
        header: "stdint.h",
        signature: "#define SIZE_MAX 18446744073709551615ULL",
        description: "Maximum value of size_t. Useful as a sentinel for size_t return values indicating error (e.g., some APIs return SIZE_MAX on failure).",
        returns: "N/A — macro constant.",
        example: "if (result == SIZE_MAX) { /* error */ }",
    },
    CFunc {
        name: "INT32_MAX",
        header: "stdint.h",
        signature: "#define INT32_MAX 2147483647",
        description: "Maximum value of int32_t. Also see INT8_MAX (127), INT16_MAX (32767), INT64_MAX (9223372036854775807).",
        returns: "N/A — macro constant.",
        example: "if (val > INT32_MAX) { /* overflow */ }",
    },
    // ── Format specifiers ────────────────────────────────────────────────────
    CFunc {
        name: "%d / %i",
        header: "format specifiers",
        signature: "%[flags][width][.precision]d",
        description: "Print/scan a signed decimal int. printf: both %d and %i are identical. scanf: %d reads base-10 only; %i auto-detects base (0x = hex, 0 = octal).",
        returns: "N/A — format specifier.",
        example: "printf(\"%d\\n\", 42);\nprintf(\"%+d\\n\", 42);  /* +42 */\nprintf(\"%08d\\n\", 7); /* 00000007 */",
    },
    CFunc {
        name: "%u",
        header: "format specifiers",
        signature: "%[flags][width][.precision]u",
        description: "Print/scan an unsigned decimal int.",
        returns: "N/A — format specifier.",
        example: "unsigned n = 300;\nprintf(\"%u\\n\", n);",
    },
    CFunc {
        name: "%ld / %li",
        header: "format specifiers",
        signature: "%[flags][width][.precision]ld",
        description: "Print/scan a signed long int. Use l (ell) length modifier with d/i for long, ll for long long.",
        returns: "N/A — format specifier.",
        example: "long x = 1234567890L;\nprintf(\"%ld\\n\", x);\nlong long y = 1LL << 40;\nprintf(\"%lld\\n\", y);",
    },
    CFunc {
        name: "%f",
        header: "format specifiers",
        signature: "%[flags][width][.precision]f",
        description: "printf: print float or double in fixed-point notation (default 6 decimal places). scanf: read into float *. Use %lf with scanf to read into double *. Width sets minimum field width; .precision sets decimal places.",
        returns: "N/A — format specifier.",
        example: "printf(\"%f\\n\", 3.14);     /* 3.140000 */\nprintf(\"%.2f\\n\", 3.14);   /* 3.14 */\nprintf(\"%8.2f\\n\", 3.14); /*     3.14 */\ndouble d; scanf(\"%lf\", &d);",
    },
    CFunc {
        name: "%lf",
        header: "format specifiers",
        signature: "%[flags][width][.precision]lf",
        description: "scanf only: read a double. In printf, %lf is identical to %f (l modifier ignored for floating-point in printf). Always use %lf with scanf for double.",
        returns: "N/A — format specifier.",
        example: "double d;\nscanf(\"%lf\", &d);\nprintf(\"%f\\n\", d); /* %f or %lf both work in printf */",
    },
    CFunc {
        name: "%e / %E",
        header: "format specifiers",
        signature: "%[flags][width][.precision]e",
        description: "Print in scientific notation: [-]d.ddddde[+-]dd. %E uses uppercase E. Default precision is 6 significant digits.",
        returns: "N/A — format specifier.",
        example: "printf(\"%e\\n\", 12345.6789); /* 1.234568e+04 */\nprintf(\"%.2e\\n\", 0.001);     /* 1.00e-03 */",
    },
    CFunc {
        name: "%g / %G",
        header: "format specifiers",
        signature: "%[flags][width][.precision]g",
        description: "Use shorter of %f or %e. Trailing zeros removed. Switches to scientific notation when exponent < -4 or >= precision (default 6). Good for general-purpose double output.",
        returns: "N/A — format specifier.",
        example: "printf(\"%g\\n\", 0.00012);  /* 0.00012 */\nprintf(\"%g\\n\", 0.000012); /* 1.2e-05 */",
    },
    CFunc {
        name: "%s",
        header: "format specifiers",
        signature: "%[flags][width][.precision]s",
        description: "Print/scan a null-terminated string. printf: .precision limits characters printed. scanf: reads until whitespace — use width to prevent overflow: scanf(\"%99s\", buf) for buf[100].",
        returns: "N/A — format specifier.",
        example: "printf(\"%s\\n\", \"hello\");\nprintf(\"%-10s|\\n\", \"hi\");  /* left-align: 'hi        |' */\nprintf(\"%.3s\\n\", \"hello\");  /* 'hel' */\nchar s[64]; scanf(\"%63s\", s);",
    },
    CFunc {
        name: "%c",
        header: "format specifiers",
        signature: "%[flags][width]c",
        description: "Print/scan a single character. scanf %c reads the next character including whitespace — use \" %c\" (note space) to skip whitespace first.",
        returns: "N/A — format specifier.",
        example: "printf(\"%c\\n\", 'A');\nchar ch; scanf(\" %c\", &ch); /* space skips newline */",
    },
    CFunc {
        name: "%p",
        header: "format specifiers",
        signature: "%p",
        description: "Print a pointer value in implementation-defined format (typically hex with 0x prefix). Cast to void * before passing.",
        returns: "N/A — format specifier.",
        example: "int x = 42;\nprintf(\"%p\\n\", (void *)&x); /* e.g. 0x7ffd1234abcd */",
    },
    CFunc {
        name: "%x / %X / %o",
        header: "format specifiers",
        signature: "%[flags][width][.precision]x",
        description: "%x: unsigned int as lowercase hex. %X: uppercase hex. %o: octal. Use # flag to prefix: %#x prints 0x..., %#o prints 0...",
        returns: "N/A — format specifier.",
        example: "printf(\"%x\\n\",  255);  /* ff */\nprintf(\"%X\\n\",  255);  /* FF */\nprintf(\"%#x\\n\", 255);  /* 0xff */\nprintf(\"%o\\n\",  8);    /* 10 */",
    },
    CFunc {
        name: "%zu",
        header: "format specifiers",
        signature: "%[flags][width]zu",
        description: "Print/scan a size_t value. Use z length modifier with u (or d for signed). Avoids warnings when printing sizeof results or array lengths on 32/64-bit platforms.",
        returns: "N/A — format specifier.",
        example: "printf(\"%zu\\n\", sizeof(int));   /* 4 */\nprintf(\"%zu\\n\", strlen(\"hi\"));  /* 2 */",
    },
    CFunc {
        name: "%%",
        header: "format specifiers",
        signature: "%%",
        description: "Print a literal percent sign. No argument consumed.",
        returns: "N/A — format specifier.",
        example: "printf(\"%.1f%%\\n\", 98.6); /* 98.6% */",
    },
    CFunc {
        name: "flags: - + 0 space #",
        header: "format specifiers",
        signature: "%[flags][width][.precision]specifier",
        description: "Format flags (may be combined): - left-justify in field; + always show sign; 0 pad with zeros instead of spaces; space prefix with space if no sign; # alternate form (%#x adds 0x, %#o adds 0, %#f always shows decimal point).",
        returns: "N/A — format modifier.",
        example: "printf(\"%-8d|\\n\", 42);  /* '42      |' left-align */\nprintf(\"%+d\\n\",  42);  /* '+42'  force sign */\nprintf(\"%08d\\n\", 42);  /* '00000042' zero-pad */",
    },
    CFunc {
        name: "width and precision",
        header: "format specifiers",
        signature: "%[width][.precision]specifier  or  %*.*specifier",
        description: "Width: minimum field width (pad with spaces or zeros). Precision: for %f/%e max decimal places; for %s max chars printed; for %d min digits. Use * to take width/precision from the next int argument.",
        returns: "N/A — format modifier.",
        example: "printf(\"%*d\\n\", 8, 42);       /* width 8 from arg: '      42' */\nprintf(\"%.*f\\n\", 3, 3.14159); /* prec 3 from arg: '3.142' */",
    },
    CFunc {
        name: "length modifiers",
        header: "format specifiers",
        signature: "h  hh  l  ll  z  t  L",
        description: "h: short; hh: char; l: long / wchar_t / double (scanf); ll: long long; z: size_t; t: ptrdiff_t; L: long double. Apply before the conversion specifier: %hd, %hhd, %ld, %lld, %lf (scanf), %Lf.",
        returns: "N/A — format modifier.",
        example: "short s; scanf(\"%hd\", &s);\nlong long n; scanf(\"%lld\", &n);\nlong double ld; printf(\"%Lf\\n\", ld);",
    },
    // ── Escape sequences ─────────────────────────────────────────────────────
    CFunc {
        name: "\\n",
        header: "escape sequences",
        signature: "\\n  (newline, ASCII 10)",
        description: "Move to the next line. Most common escape. On POSIX, text files end each line with \\n. On Windows, files use \\r\\n — fopen in text mode handles the conversion.",
        returns: "N/A — escape sequence.",
        example: "printf(\"Line 1\\nLine 2\\n\");",
    },
    CFunc {
        name: "\\t",
        header: "escape sequences",
        signature: "\\t  (horizontal tab, ASCII 9)",
        description: "Horizontal tab. Advances to the next tab stop (typically every 8 columns, but terminal-dependent). Often used to align columns in plain-text output.",
        returns: "N/A — escape sequence.",
        example: "printf(\"Name:\\tSam\\n\");",
    },
    CFunc {
        name: "\\r",
        header: "escape sequences",
        signature: "\\r  (carriage return, ASCII 13)",
        description: "Move cursor to beginning of current line without advancing. On its own causes overwrite. Combined as \\r\\n it is the Windows line ending.",
        returns: "N/A — escape sequence.",
        example: "printf(\"Progress: %d%%\\r\", pct); /* overwrite same line */\nfflush(stdout);",
    },
    CFunc {
        name: "\\0",
        header: "escape sequences",
        signature: "\\0  (null character, ASCII 0)",
        description: "Null terminator — marks the end of a C string. Every string literal has an implicit \\0 appended. Do not confuse with '0' (ASCII 48) or 0 (integer zero).",
        returns: "N/A — escape sequence.",
        example: "char s[5] = {'h','i','\\0','?','?'}; /* strlen(s) == 2 */\nif (s[0] == '\\0') { /* empty string */ }",
    },
    CFunc {
        name: "\\\\",
        header: "escape sequences",
        signature: "\\\\  (backslash, ASCII 92)",
        description: "Literal backslash character. Required because \\ is the escape prefix.",
        returns: "N/A — escape sequence.",
        example: "printf(\"C:\\\\Users\\\\sam\\n\"); /* C:\\Users\\sam */",
    },
    CFunc {
        name: "\\\"",
        header: "escape sequences",
        signature: "\\\"  (double quote, ASCII 34)",
        description: "Literal double-quote inside a string literal.",
        returns: "N/A — escape sequence.",
        example: "printf(\"She said \\\"hello\\\"\\n\");",
    },
    CFunc {
        name: "\\'",
        header: "escape sequences",
        signature: "\\'  (single quote, ASCII 39)",
        description: "Literal single-quote inside a character literal. Not required inside string literals but valid.",
        returns: "N/A — escape sequence.",
        example: "char c = '\\'';",
    },
    CFunc {
        name: "\\a",
        header: "escape sequences",
        signature: "\\a  (alert/bell, ASCII 7)",
        description: "Ring the terminal bell (audible or visual). Rarely used in modern code.",
        returns: "N/A — escape sequence.",
        example: "printf(\"\\a\"); /* beep */",
    },
    CFunc {
        name: "\\b",
        header: "escape sequences",
        signature: "\\b  (backspace, ASCII 8)",
        description: "Move cursor one position back. In terminal output this can erase the previous character, but behaviour varies.",
        returns: "N/A — escape sequence.",
        example: "printf(\"hello\\b \"); /* erase last char */",
    },
    CFunc {
        name: "\\f",
        header: "escape sequences",
        signature: "\\f  (form feed, ASCII 12)",
        description: "Advance to next page on a printer. Mostly obsolete in modern code.",
        returns: "N/A — escape sequence.",
        example: "fprintf(printer_fp, \"Page 1\\fPage 2\");",
    },
    CFunc {
        name: "\\v",
        header: "escape sequences",
        signature: "\\v  (vertical tab, ASCII 11)",
        description: "Vertical tab — move cursor down by one tab stop. Rarely used.",
        returns: "N/A — escape sequence.",
        example: "printf(\"line1\\vline2\");",
    },
    CFunc {
        name: "\\xHH",
        header: "escape sequences",
        signature: "\\xHH  (hex escape, one or more hex digits)",
        description: "Character with hexadecimal value HH. Reads as many hex digits as follow. Warning: \\x41 == 'A'. Be careful in string literals — \\x41bc reads all of '4','1','b','c' as one escape.",
        returns: "N/A — escape sequence.",
        example: "printf(\"\\x41\\n\");  /* A */\nchar esc = '\\x1B'; /* ESC key */",
    },
    CFunc {
        name: "\\NNN",
        header: "escape sequences",
        signature: "\\NNN  (octal escape, 1–3 octal digits)",
        description: "Character with octal value NNN. At most 3 octal digits read. \\0 is the null terminator (octal 0).",
        returns: "N/A — escape sequence.",
        example: "printf(\"\\101\\n\"); /* A (octal 101 = decimal 65) */\nchar nul = '\\0'; /* null */",
    },
    // ── Operator precedence ──────────────────────────────────────────────────
    CFunc {
        name: "Prec 1 — Postfix  (L→R)",
        header: "operator precedence",
        signature: "expr()  expr[]  expr.member  expr->member  expr++  expr--",
        description: "Highest precedence. Function call, array subscript, struct member access (dot and arrow), postfix increment/decrement. Left-to-right associative.",
        returns: "N/A — precedence reference.",
        example: "arr[i]++;        /* subscript then increment */\np->x;            /* arrow = (*p).x */",
    },
    CFunc {
        name: "Prec 2 — Prefix/Unary  (R→L)",
        header: "operator precedence",
        signature: "++expr  --expr  +expr  -expr  !expr  ~expr  *expr  &expr  (type)expr  sizeof",
        description: "Unary operators: prefix increment/decrement, unary plus/minus, logical NOT, bitwise NOT, dereference, address-of, cast, sizeof. Right-to-left associative.",
        returns: "N/A — precedence reference.",
        example: "!flag;        /* logical NOT */\n*ptr;         /* dereference */\n&var;         /* address-of */\n(int)3.14;   /* cast */\nsizeof(int); /* size in bytes */",
    },
    CFunc {
        name: "Prec 3 — Multiplicative  (L→R)",
        header: "operator precedence",
        signature: "expr * expr   expr / expr   expr % expr",
        description: "Multiplication, division, modulo. Integer division truncates toward zero. Modulo result has same sign as the dividend in C99+.",
        returns: "N/A — precedence reference.",
        example: "7 / 2;   /* 3 (integer truncation) */\n7 % 2;   /* 1 */\n-7 % 2;  /* -1 (same sign as dividend) */",
    },
    CFunc {
        name: "Prec 4 — Additive  (L→R)",
        header: "operator precedence",
        signature: "expr + expr   expr - expr",
        description: "Addition and subtraction.",
        returns: "N/A — precedence reference.",
        example: "2 + 3 * 4;  /* 14, not 20 — * binds tighter */",
    },
    CFunc {
        name: "Prec 5 — Shift  (L→R)",
        header: "operator precedence",
        signature: "expr << expr   expr >> expr",
        description: "Bitwise left-shift and right-shift. Left-shift by n = multiply by 2^n. Right-shift on signed values is implementation-defined (arithmetic vs logical); use unsigned types.",
        returns: "N/A — precedence reference.",
        example: "1 << 4;    /* 16 */\n256 >> 3;  /* 32 */",
    },
    CFunc {
        name: "Prec 6 — Relational  (L→R)",
        header: "operator precedence",
        signature: "expr < expr   expr > expr   expr <= expr   expr >= expr",
        description: "Comparison operators. Return int 0 (false) or 1 (true). Lower precedence than arithmetic, so a + b < c + d works as expected.",
        returns: "N/A — precedence reference.",
        example: "3 + 4 < 10;   /* 1 (true) */\n/* Don't chain: 1 < x < 10 is (1<x)<10, always true if x>=1 */",
    },
    CFunc {
        name: "Prec 7 — Equality  (L→R)",
        header: "operator precedence",
        signature: "expr == expr   expr != expr",
        description: "Equality and inequality. Lower than relational operators. Common mistake: use = (assignment) instead of == (comparison) — the compiler warns with -Wall.",
        returns: "N/A — precedence reference.",
        example: "if (x == 0) { /* x is zero */ }\nif (x != y) { /* x and y differ */ }",
    },
    CFunc {
        name: "Prec 8 — Bitwise AND  (L→R)",
        header: "operator precedence",
        signature: "expr & expr",
        description: "Bitwise AND. Used for masking bits. Lower precedence than == — always parenthesise: (flags & MASK) == MASK, not flags & MASK == MASK.",
        returns: "N/A — precedence reference.",
        example: "int masked = value & 0xFF; /* keep low 8 bits */\nif ((flags & READ_FLAG) != 0) { /* flag set */ }",
    },
    CFunc {
        name: "Prec 9 — Bitwise XOR  (L→R)",
        header: "operator precedence",
        signature: "expr ^ expr",
        description: "Bitwise exclusive OR. Bit is 1 if inputs differ. Used for toggling flags and simple checksums.",
        returns: "N/A — precedence reference.",
        example: "flags ^= TOGGLE_BIT; /* flip a flag */\na ^= b; b ^= a; a ^= b; /* swap without temp */",
    },
    CFunc {
        name: "Prec 10 — Bitwise OR  (L→R)",
        header: "operator precedence",
        signature: "expr | expr",
        description: "Bitwise OR. Used for setting flags. Lower precedence than == — parenthesise comparisons.",
        returns: "N/A — precedence reference.",
        example: "flags |= READ_FLAG | WRITE_FLAG; /* set two flags */",
    },
    CFunc {
        name: "Prec 11 — Logical AND  (L→R)",
        header: "operator precedence",
        signature: "expr && expr",
        description: "Logical AND. Short-circuits: right side not evaluated if left is false. Returns int 0 or 1.",
        returns: "N/A — precedence reference.",
        example: "if (ptr != NULL && ptr->val > 0) { /* safe */ }",
    },
    CFunc {
        name: "Prec 12 — Logical OR  (L→R)",
        header: "operator precedence",
        signature: "expr || expr",
        description: "Logical OR. Short-circuits: right side not evaluated if left is true. Returns int 0 or 1.",
        returns: "N/A — precedence reference.",
        example: "if (err == ENOENT || err == EACCES) { /* handle */ }",
    },
    CFunc {
        name: "Prec 13 — Conditional  (R→L)",
        header: "operator precedence",
        signature: "condition ? expr_if_true : expr_if_false",
        description: "Ternary operator. Evaluates condition; returns second operand if true, third if false. Right-to-left associative. Useful for compact conditional expressions — avoid nesting.",
        returns: "N/A — precedence reference.",
        example: "int abs_x = (x >= 0) ? x : -x;\nprintf(\"%s\\n\", (n == 1) ? \"item\" : \"items\");",
    },
    CFunc {
        name: "Prec 14 — Assignment  (R→L)",
        header: "operator precedence",
        signature: "=  +=  -=  *=  /=  %=  &=  ^=  |=  <<=  >>=",
        description: "Assignment and compound assignment. Right-to-left: a = b = 0 assigns 0 to b then a. Compound: a += b is shorthand for a = a + b.",
        returns: "N/A — precedence reference.",
        example: "a = b = c = 0;    /* chain assignment */\nx += 5;           /* x = x + 5 */\nflags &= ~MASK;   /* clear bits */",
    },
    CFunc {
        name: "Prec 15 — Comma  (L→R)",
        header: "operator precedence",
        signature: "expr , expr",
        description: "Lowest precedence. Evaluates left then right; result is the right operand. Mainly used in for-loop init/increment clauses. Avoid in other contexts — confusing.",
        returns: "N/A — precedence reference.",
        example: "for (int i = 0, j = n-1; i < j; i++, j--) { /* swap */ }\nint x = (a = 1, b = 2, a + b); /* x == 3, avoid this */",
    },
];
