/// Static C standard library reference data.

#[derive(Debug, Clone, Copy)]
pub struct CFunc {
    pub name: &'static str,
    pub header: &'static str,
    pub signature: &'static str,
    pub description: &'static str,
    pub returns: &'static str,
    pub example: &'static str,
}

pub fn all_functions() -> &'static [CFunc] {
    CFUNCS
}

pub fn headers() -> Vec<&'static str> {
    let mut h: Vec<&'static str> = CFUNCS.iter().map(|f| f.header).collect();
    h.sort();
    h.dedup();
    h
}

pub fn by_header(header: &str) -> Vec<&'static CFunc> {
    CFUNCS.iter().filter(|f| f.header == header).collect()
}

pub fn search(query: &str) -> Vec<&'static CFunc> {
    let q = query.to_lowercase();
    CFUNCS.iter().filter(|f| {
        f.name.to_lowercase().contains(&q)
            || f.description.to_lowercase().contains(&q)
            || f.signature.to_lowercase().contains(&q)
    }).collect()
}

static CFUNCS: &[CFunc] = &[
    // ── stdio.h ──────────────────────────────────────────────────────────────
    CFunc { name: "printf", header: "stdio.h",
        signature: "int printf(const char *format, ...)",
        description: "Print formatted output to stdout. Format specifiers: %d (int), %f (double), %s (string), %c (char), %ld (long), %lf (double), %p (pointer).",
        returns: "Number of characters written, or negative on error.",
        example: "printf(\"Value: %d\\n\", 42);" },
    CFunc { name: "scanf", header: "stdio.h",
        signature: "int scanf(const char *format, ...)",
        description: "Read formatted input from stdin. Pass addresses of variables. %d reads int, %lf reads double, %s reads word (no spaces).",
        returns: "Number of items successfully matched and assigned.",
        example: "int n; scanf(\"%d\", &n);" },
    CFunc { name: "fprintf", header: "stdio.h",
        signature: "int fprintf(FILE *stream, const char *format, ...)",
        description: "Write formatted output to a file stream (or stderr for error messages).",
        returns: "Number of characters written, or negative on error.",
        example: "fprintf(stderr, \"Error: %s\\n\", msg);" },
    CFunc { name: "fscanf", header: "stdio.h",
        signature: "int fscanf(FILE *stream, const char *format, ...)",
        description: "Read formatted data from a file stream.",
        returns: "Number of items matched, or EOF on end-of-file or error.",
        example: "int x; fscanf(fp, \"%d\", &x);" },
    CFunc { name: "sprintf", header: "stdio.h",
        signature: "int sprintf(char *str, const char *format, ...)",
        description: "Write formatted output into a string buffer. Ensure buffer is large enough.",
        returns: "Number of characters written (not counting null terminator).",
        example: "char buf[64]; sprintf(buf, \"%d items\", count);" },
    CFunc { name: "snprintf", header: "stdio.h",
        signature: "int snprintf(char *str, size_t size, const char *format, ...)",
        description: "Safer sprintf — writes at most size-1 characters and always null-terminates.",
        returns: "Number of characters that would have been written if size were unlimited.",
        example: "snprintf(buf, sizeof(buf), \"%s: %d\", label, val);" },
    CFunc { name: "sscanf", header: "stdio.h",
        signature: "int sscanf(const char *str, const char *format, ...)",
        description: "Read formatted data from a string rather than stdin.",
        returns: "Number of items matched.",
        example: "int n; sscanf(\"42\", \"%d\", &n);" },
    CFunc { name: "fopen", header: "stdio.h",
        signature: "FILE *fopen(const char *filename, const char *mode)",
        description: "Open a file. Modes: \"r\" read, \"w\" write (truncate), \"a\" append, \"r+\" read+write, \"rb\" binary read, \"wb\" binary write.",
        returns: "FILE pointer, or NULL on failure.",
        example: "FILE *fp = fopen(\"data.txt\", \"r\");\nif (!fp) { perror(\"fopen\"); exit(1); }" },
    CFunc { name: "fclose", header: "stdio.h",
        signature: "int fclose(FILE *stream)",
        description: "Close an open file stream and flush its buffer. Always close files you open.",
        returns: "0 on success, EOF on error.",
        example: "fclose(fp);" },
    CFunc { name: "fgets", header: "stdio.h",
        signature: "char *fgets(char *str, int n, FILE *stream)",
        description: "Read at most n-1 characters from stream into str, stopping at newline or EOF. Includes the newline. Safer than gets().",
        returns: "str on success, NULL on EOF or error.",
        example: "char line[256]; fgets(line, sizeof(line), stdin);" },
    CFunc { name: "fputs", header: "stdio.h",
        signature: "int fputs(const char *str, FILE *stream)",
        description: "Write string str to stream (without adding a newline).",
        returns: "Non-negative on success, EOF on error.",
        example: "fputs(\"Hello\\n\", stdout);" },
    CFunc { name: "fread", header: "stdio.h",
        signature: "size_t fread(void *ptr, size_t size, size_t count, FILE *stream)",
        description: "Read count elements of size bytes each from stream into ptr. Used for binary files.",
        returns: "Number of elements successfully read (may be less than count on EOF/error).",
        example: "fread(buf, sizeof(int), 10, fp);" },
    CFunc { name: "fwrite", header: "stdio.h",
        signature: "size_t fwrite(const void *ptr, size_t size, size_t count, FILE *stream)",
        description: "Write count elements of size bytes each from ptr to stream.",
        returns: "Number of elements successfully written.",
        example: "fwrite(arr, sizeof(int), size, fp);" },
    CFunc { name: "feof", header: "stdio.h",
        signature: "int feof(FILE *stream)",
        description: "Test end-of-file indicator for stream. Note: returns non-zero AFTER a read fails at EOF, not before.",
        returns: "Non-zero if at end-of-file, 0 otherwise.",
        example: "while (!feof(fp)) { fgets(line, sizeof(line), fp); }" },
    CFunc { name: "fseek", header: "stdio.h",
        signature: "int fseek(FILE *stream, long offset, int whence)",
        description: "Move file position. whence: SEEK_SET (from start), SEEK_CUR (from current), SEEK_END (from end).",
        returns: "0 on success, non-zero on error.",
        example: "fseek(fp, 0, SEEK_SET); /* rewind */" },
    CFunc { name: "ftell", header: "stdio.h",
        signature: "long ftell(FILE *stream)",
        description: "Return current file position (byte offset from start).",
        returns: "Current position, or -1L on error.",
        example: "long pos = ftell(fp);" },
    CFunc { name: "rewind", header: "stdio.h",
        signature: "void rewind(FILE *stream)",
        description: "Reset file position to start and clear error/EOF indicators.",
        returns: "Nothing.",
        example: "rewind(fp);" },
    CFunc { name: "puts", header: "stdio.h",
        signature: "int puts(const char *str)",
        description: "Write str to stdout followed by a newline. Simpler than printf for plain strings.",
        returns: "Non-negative on success, EOF on error.",
        example: "puts(\"Hello, world!\");" },
    CFunc { name: "getchar", header: "stdio.h",
        signature: "int getchar(void)",
        description: "Read one character from stdin. Returns int to distinguish EOF (-1) from valid chars.",
        returns: "Character read as unsigned char cast to int, or EOF.",
        example: "int c = getchar();" },
    CFunc { name: "putchar", header: "stdio.h",
        signature: "int putchar(int c)",
        description: "Write one character to stdout.",
        returns: "Character written, or EOF on error.",
        example: "putchar('A');" },
    CFunc { name: "perror", header: "stdio.h",
        signature: "void perror(const char *str)",
        description: "Print str followed by a colon and the string for the current errno error. Useful after failed system calls.",
        returns: "Nothing.",
        example: "FILE *fp = fopen(\"x\", \"r\");\nif (!fp) { perror(\"fopen\"); exit(1); }" },
    CFunc { name: "remove", header: "stdio.h",
        signature: "int remove(const char *filename)",
        description: "Delete a file.",
        returns: "0 on success, non-zero on error.",
        example: "remove(\"temp.txt\");" },
    CFunc { name: "rename", header: "stdio.h",
        signature: "int rename(const char *old, const char *new)",
        description: "Rename or move a file.",
        returns: "0 on success, non-zero on error.",
        example: "rename(\"old.txt\", \"new.txt\");" },

    // ── stdlib.h ─────────────────────────────────────────────────────────────
    CFunc { name: "malloc", header: "stdlib.h",
        signature: "void *malloc(size_t size)",
        description: "Allocate size bytes of uninitialised heap memory. Always check for NULL return. Must be freed with free().",
        returns: "Pointer to allocated memory, or NULL on failure.",
        example: "int *arr = malloc(n * sizeof(int));\nif (!arr) { perror(\"malloc\"); exit(1); }" },
    CFunc { name: "calloc", header: "stdlib.h",
        signature: "void *calloc(size_t count, size_t size)",
        description: "Allocate count*size bytes, initialised to zero. Prefer over malloc when you need zero-initialisation.",
        returns: "Pointer to zeroed memory, or NULL on failure.",
        example: "int *arr = calloc(n, sizeof(int));" },
    CFunc { name: "realloc", header: "stdlib.h",
        signature: "void *realloc(void *ptr, size_t new_size)",
        description: "Resize a previously allocated block. May move it. If ptr is NULL, behaves like malloc. If new_size is 0, frees ptr.",
        returns: "New pointer (may differ from ptr), or NULL on failure (original ptr still valid).",
        example: "arr = realloc(arr, new_n * sizeof(int));" },
    CFunc { name: "free", header: "stdlib.h",
        signature: "void free(void *ptr)",
        description: "Release heap memory allocated by malloc/calloc/realloc. Passing NULL is safe (no-op). Never free the same pointer twice.",
        returns: "Nothing.",
        example: "free(arr); arr = NULL;" },
    CFunc { name: "exit", header: "stdlib.h",
        signature: "void exit(int status)",
        description: "Terminate the program. Flushes stdio buffers and runs atexit() handlers. Status 0 or EXIT_SUCCESS = normal, EXIT_FAILURE = error.",
        returns: "Does not return.",
        example: "if (error) exit(EXIT_FAILURE);" },
    CFunc { name: "atoi", header: "stdlib.h",
        signature: "int atoi(const char *str)",
        description: "Convert string to int. Does not detect errors — use strtol() for robust conversion.",
        returns: "Integer value, or 0 if conversion fails.",
        example: "int n = atoi(\"42\");" },
    CFunc { name: "atof", header: "stdlib.h",
        signature: "double atof(const char *str)",
        description: "Convert string to double. Does not detect errors — use strtod() for robust conversion.",
        returns: "Double value, or 0.0 if conversion fails.",
        example: "double d = atof(\"3.14\");" },
    CFunc { name: "strtol", header: "stdlib.h",
        signature: "long strtol(const char *str, char **endptr, int base)",
        description: "Robust string-to-long conversion. endptr points past the last character used; base is 10 for decimal, 0 for auto-detect.",
        returns: "Converted long value.",
        example: "char *end; long n = strtol(\"42\", &end, 10);" },
    CFunc { name: "strtod", header: "stdlib.h",
        signature: "double strtod(const char *str, char **endptr)",
        description: "Robust string-to-double conversion. *endptr points past last character used.",
        returns: "Converted double value.",
        example: "char *end; double d = strtod(\"3.14\", &end);" },
    CFunc { name: "rand", header: "stdlib.h",
        signature: "int rand(void)",
        description: "Generate a pseudo-random integer in [0, RAND_MAX]. Seed with srand() first.",
        returns: "Random integer in [0, RAND_MAX].",
        example: "srand(time(NULL)); int r = rand() % 100;" },
    CFunc { name: "srand", header: "stdlib.h",
        signature: "void srand(unsigned int seed)",
        description: "Seed the random number generator. Call once at program start. srand(time(NULL)) uses current time.",
        returns: "Nothing.",
        example: "srand((unsigned int)time(NULL));" },
    CFunc { name: "abs", header: "stdlib.h",
        signature: "int abs(int n)",
        description: "Absolute value of an int.",
        returns: "Absolute value of n.",
        example: "int a = abs(-5); /* 5 */" },
    CFunc { name: "qsort", header: "stdlib.h",
        signature: "void qsort(void *base, size_t count, size_t size, int (*compare)(const void *, const void *))",
        description: "Sort array in-place. compare(a,b) returns <0 if a<b, 0 if equal, >0 if a>b.",
        returns: "Nothing.",
        example: "int cmp(const void *a, const void *b) { return *(int*)a - *(int*)b; }\nqsort(arr, n, sizeof(int), cmp);" },
    CFunc { name: "bsearch", header: "stdlib.h",
        signature: "void *bsearch(const void *key, const void *base, size_t count, size_t size, int (*compare)(const void *, const void *))",
        description: "Binary search in sorted array. compare function same as qsort.",
        returns: "Pointer to matching element, or NULL if not found.",
        example: "int *p = bsearch(&target, arr, n, sizeof(int), cmp);" },

    // ── string.h ─────────────────────────────────────────────────────────────
    CFunc { name: "strlen", header: "string.h",
        signature: "size_t strlen(const char *s)",
        description: "Return length of string s, not counting the null terminator.",
        returns: "Number of characters before '\\0'.",
        example: "size_t len = strlen(\"hello\"); /* 5 */" },
    CFunc { name: "strcpy", header: "string.h",
        signature: "char *strcpy(char *dest, const char *src)",
        description: "Copy src into dest including null terminator. dest must be large enough. Prefer strncpy for safety.",
        returns: "dest.",
        example: "char buf[64]; strcpy(buf, \"hello\");" },
    CFunc { name: "strncpy", header: "string.h",
        signature: "char *strncpy(char *dest, const char *src, size_t n)",
        description: "Copy at most n characters from src to dest. If src is shorter, pads with '\\0'. If src is longer, result may not be null-terminated — add '\\0' manually.",
        returns: "dest.",
        example: "strncpy(buf, src, sizeof(buf) - 1); buf[sizeof(buf)-1] = '\\0';" },
    CFunc { name: "strcat", header: "string.h",
        signature: "char *strcat(char *dest, const char *src)",
        description: "Append src to end of dest. dest must have enough space for both strings.",
        returns: "dest.",
        example: "strcat(buf, \" world\");" },
    CFunc { name: "strncat", header: "string.h",
        signature: "char *strncat(char *dest, const char *src, size_t n)",
        description: "Append at most n characters of src to dest. Always null-terminates.",
        returns: "dest.",
        example: "strncat(buf, src, sizeof(buf) - strlen(buf) - 1);" },
    CFunc { name: "strcmp", header: "string.h",
        signature: "int strcmp(const char *s1, const char *s2)",
        description: "Compare two strings lexicographically.",
        returns: "<0 if s1 < s2, 0 if equal, >0 if s1 > s2.",
        example: "if (strcmp(s1, s2) == 0) { /* strings are equal */ }" },
    CFunc { name: "strncmp", header: "string.h",
        signature: "int strncmp(const char *s1, const char *s2, size_t n)",
        description: "Compare at most n characters of two strings.",
        returns: "<0, 0, or >0 as strcmp.",
        example: "strncmp(s1, s2, 3);" },
    CFunc { name: "strchr", header: "string.h",
        signature: "char *strchr(const char *s, int c)",
        description: "Find first occurrence of character c in string s.",
        returns: "Pointer to character, or NULL if not found.",
        example: "char *p = strchr(s, 'a');" },
    CFunc { name: "strrchr", header: "string.h",
        signature: "char *strrchr(const char *s, int c)",
        description: "Find last occurrence of character c in string s.",
        returns: "Pointer to last occurrence, or NULL if not found.",
        example: "char *last = strrchr(path, '/');" },
    CFunc { name: "strstr", header: "string.h",
        signature: "char *strstr(const char *haystack, const char *needle)",
        description: "Find first occurrence of substring needle in string haystack.",
        returns: "Pointer to start of needle in haystack, or NULL if not found.",
        example: "char *pos = strstr(text, \"hello\");" },
    CFunc { name: "strtok", header: "string.h",
        signature: "char *strtok(char *str, const char *delimiters)",
        description: "Split string into tokens. First call passes str; subsequent calls pass NULL. Modifies the string in-place.",
        returns: "Pointer to next token, or NULL when done.",
        example: "char *tok = strtok(line, \",\");\nwhile (tok) { printf(\"%s\\n\", tok); tok = strtok(NULL, \",\"); }" },
    CFunc { name: "memset", header: "string.h",
        signature: "void *memset(void *ptr, int value, size_t count)",
        description: "Fill count bytes of memory at ptr with value (interpreted as unsigned char). Useful for zeroing arrays.",
        returns: "ptr.",
        example: "memset(arr, 0, sizeof(arr));" },
    CFunc { name: "memcpy", header: "string.h",
        signature: "void *memcpy(void *dest, const void *src, size_t count)",
        description: "Copy count bytes from src to dest. Regions must not overlap — use memmove for overlapping regions.",
        returns: "dest.",
        example: "memcpy(dest_arr, src_arr, n * sizeof(int));" },
    CFunc { name: "memmove", header: "string.h",
        signature: "void *memmove(void *dest, const void *src, size_t count)",
        description: "Copy count bytes from src to dest, handling overlapping regions correctly.",
        returns: "dest.",
        example: "memmove(arr + 1, arr, (n-1) * sizeof(int));" },
    CFunc { name: "memcmp", header: "string.h",
        signature: "int memcmp(const void *s1, const void *s2, size_t count)",
        description: "Compare count bytes of memory at s1 and s2.",
        returns: "<0, 0, or >0.",
        example: "memcmp(a, b, sizeof(a));" },

    // ── math.h ───────────────────────────────────────────────────────────────
    CFunc { name: "sqrt", header: "math.h",
        signature: "double sqrt(double x)",
        description: "Square root of x. Compile with -lm on Linux.",
        returns: "Square root of x, or NaN if x < 0.",
        example: "double r = sqrt(2.0);" },
    CFunc { name: "pow", header: "math.h",
        signature: "double pow(double base, double exp)",
        description: "base raised to the power exp. For integer exponents prefer manual multiplication.",
        returns: "base^exp.",
        example: "double r = pow(2.0, 10.0); /* 1024.0 */" },
    CFunc { name: "fabs", header: "math.h",
        signature: "double fabs(double x)",
        description: "Absolute value of a double.",
        returns: "|x|.",
        example: "double a = fabs(-3.14);" },
    CFunc { name: "ceil", header: "math.h",
        signature: "double ceil(double x)",
        description: "Round x up to the nearest integer (toward +infinity).",
        returns: "Smallest integer >= x as double.",
        example: "ceil(1.2); /* 2.0 */" },
    CFunc { name: "floor", header: "math.h",
        signature: "double floor(double x)",
        description: "Round x down to the nearest integer (toward -infinity).",
        returns: "Largest integer <= x as double.",
        example: "floor(1.9); /* 1.0 */" },
    CFunc { name: "round", header: "math.h",
        signature: "double round(double x)",
        description: "Round x to the nearest integer, with halfway cases away from zero.",
        returns: "Nearest integer as double.",
        example: "round(1.5); /* 2.0 */" },
    CFunc { name: "fmod", header: "math.h",
        signature: "double fmod(double x, double y)",
        description: "Floating-point remainder of x/y (same sign as x).",
        returns: "x - n*y where n is the truncated quotient.",
        example: "fmod(5.5, 2.0); /* 1.5 */" },
    CFunc { name: "log", header: "math.h",
        signature: "double log(double x)",
        description: "Natural logarithm (base e) of x.",
        returns: "ln(x), or -infinity if x=0, NaN if x<0.",
        example: "double r = log(2.71828);" },
    CFunc { name: "log10", header: "math.h",
        signature: "double log10(double x)",
        description: "Base-10 logarithm of x.",
        returns: "log10(x).",
        example: "log10(100.0); /* 2.0 */" },
    CFunc { name: "sin", header: "math.h",
        signature: "double sin(double x)",
        description: "Sine of x in radians.",
        returns: "sin(x) in [-1, 1].",
        example: "sin(3.14159 / 2.0); /* ~1.0 */" },
    CFunc { name: "cos", header: "math.h",
        signature: "double cos(double x)",
        description: "Cosine of x in radians.",
        returns: "cos(x) in [-1, 1].",
        example: "cos(0.0); /* 1.0 */" },
    CFunc { name: "tan", header: "math.h",
        signature: "double tan(double x)",
        description: "Tangent of x in radians.",
        returns: "tan(x).",
        example: "tan(3.14159 / 4.0); /* ~1.0 */" },
    CFunc { name: "exp", header: "math.h",
        signature: "double exp(double x)",
        description: "e raised to the power x.",
        returns: "e^x.",
        example: "exp(1.0); /* ~2.71828 */" },

    // ── time.h ───────────────────────────────────────────────────────────────
    CFunc { name: "time", header: "time.h",
        signature: "time_t time(time_t *tloc)",
        description: "Return current calendar time as seconds since epoch (1 Jan 1970). Pass NULL if you don't need the pointer filled.",
        returns: "Current time as time_t, or -1 on error.",
        example: "time_t now = time(NULL);" },
    CFunc { name: "clock", header: "time.h",
        signature: "clock_t clock(void)",
        description: "Return processor time used by the program. Divide by CLOCKS_PER_SEC for seconds.",
        returns: "CPU time as clock_t.",
        example: "clock_t start = clock();\n/* ... */\ndouble elapsed = (double)(clock() - start) / CLOCKS_PER_SEC;" },
    CFunc { name: "difftime", header: "time.h",
        signature: "double difftime(time_t end, time_t start)",
        description: "Compute difference between two time_t values in seconds.",
        returns: "end - start as double.",
        example: "double secs = difftime(end_time, start_time);" },
    CFunc { name: "localtime", header: "time.h",
        signature: "struct tm *localtime(const time_t *timer)",
        description: "Convert time_t to broken-down local time (struct tm with tm_year, tm_mon, tm_mday, tm_hour, tm_min, tm_sec etc.).",
        returns: "Pointer to static struct tm (not thread-safe).",
        example: "time_t t = time(NULL);\nstruct tm *lt = localtime(&t);\nprintf(\"%d-%02d-%02d\\n\", lt->tm_year+1900, lt->tm_mon+1, lt->tm_mday);" },
    CFunc { name: "strftime", header: "time.h",
        signature: "size_t strftime(char *s, size_t max, const char *format, const struct tm *tm)",
        description: "Format broken-down time as string. Common formats: %Y year, %m month, %d day, %H hour, %M minute, %S second.",
        returns: "Number of characters placed in s (not counting '\\0'), or 0 if buffer too small.",
        example: "char buf[64];\nstrftime(buf, sizeof(buf), \"%Y-%m-%d %H:%M:%S\", localtime(&t));" },

    // ── ctype.h ──────────────────────────────────────────────────────────────
    CFunc { name: "isalpha", header: "ctype.h",
        signature: "int isalpha(int c)",
        description: "Test if c is an alphabetic letter (a-z or A-Z).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "if (isalpha(c)) { /* letter */ }" },
    CFunc { name: "isdigit", header: "ctype.h",
        signature: "int isdigit(int c)",
        description: "Test if c is a decimal digit (0-9).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "if (isdigit(c)) { /* digit */ }" },
    CFunc { name: "isalnum", header: "ctype.h",
        signature: "int isalnum(int c)",
        description: "Test if c is alphanumeric (letter or digit).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "if (isalnum(c)) { /* alphanumeric */ }" },
    CFunc { name: "isspace", header: "ctype.h",
        signature: "int isspace(int c)",
        description: "Test if c is a whitespace character (space, tab, newline, etc.).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "while (isspace(*p)) p++; /* skip whitespace */" },
    CFunc { name: "isupper", header: "ctype.h",
        signature: "int isupper(int c)",
        description: "Test if c is an uppercase letter (A-Z).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "if (isupper(c)) { /* uppercase */ }" },
    CFunc { name: "islower", header: "ctype.h",
        signature: "int islower(int c)",
        description: "Test if c is a lowercase letter (a-z).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "if (islower(c)) { /* lowercase */ }" },
    CFunc { name: "toupper", header: "ctype.h",
        signature: "int toupper(int c)",
        description: "Convert lowercase letter to uppercase. Non-letter characters unchanged.",
        returns: "Uppercase equivalent, or c unchanged.",
        example: "char u = (char)toupper('a'); /* 'A' */" },
    CFunc { name: "tolower", header: "ctype.h",
        signature: "int tolower(int c)",
        description: "Convert uppercase letter to lowercase. Non-letter characters unchanged.",
        returns: "Lowercase equivalent, or c unchanged.",
        example: "char l = (char)tolower('A'); /* 'a' */" },
    CFunc { name: "ispunct", header: "ctype.h",
        signature: "int ispunct(int c)",
        description: "Test if c is a punctuation character (printable but not alphanumeric or space).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "if (ispunct(c)) { /* punctuation */ }" },
    CFunc { name: "isprint", header: "ctype.h",
        signature: "int isprint(int c)",
        description: "Test if c is a printable character (including space).",
        returns: "Non-zero if true, 0 otherwise.",
        example: "if (isprint(c)) putchar(c);" },
];
